export const translations = {
  bs: {
    localeName: 'Bosanski',
    nav: { services: 'Usluge', process: 'Kako radimo', pricing: 'Cijene', faq: 'Pitanja', book: 'Zakažite razgovor', language: 'Jezik' },
    hero: {
      eyebrow: 'Evropske prijave · Balkan i dijaspora',
      titleA: 'Prava prijava ne počinje formularom.',
      titleB: 'Počinje pravcem.',
      body: 'Individualno, nezavisno savjetovanje za studije u inostranstvu — od izbora programa do prijave koja jasno predstavlja ko ste.',
      primary: 'Zakažite besplatan razgovor',
      secondary: 'Pogledajte usluge',
    },
    trust: ['Nezavisno savjetovanje', 'Rad 1 na 1', 'Jasne cijene'],
    route: {
      title: 'Vaša admissions ruta', live: 'jasno', next: 'Sljedeći korak', free: '15 min · bez naknade',
      stops: [['PROFIL', 'Polazna tačka'], ['SMJER', 'Pravi programi'], ['PRIJAVA', 'Jasna priča']],
      note: 'Ne biramo univerzitet umjesto vas. Pomažemo da donesete bolju odluku.',
    },
    signals: {
      kicker: 'Prije prve prijave',
      title: 'Prvo mapiramo odluke koje zapravo određuju ishod.',
      body: 'Dobra strategija povezuje akademski profil, finansije, rokove i ambiciju. Tek onda biramo programe i oblikujemo prijavu.',
      items: [
        ['Akademski fit', 'Procjenjujemo gdje je vaš profil konkurentan i gdje treba ojačati priču.'],
        ['Budžet i stipendije', 'Troškove i realne izvore finansiranja uključujemo od prvog dana.'],
        ['Programi i zemlje', 'Ne pravimo generičku listu; svaki izbor mora imati jasan razlog.'],
        ['Rokovi i ritam', 'Kompleksan proces pretvaramo u prioritete, rokove i sedmični plan.'],
      ],
    },
    services: {
      kicker: 'Usluge',
      title: 'Podrška onoliko široka koliko vam zaista treba.',
      body: 'Počnite jednom strateškom sesijom ili radite s nama kroz cijeli prijavni ciklus.',
      cta: 'Razgovarajmo o vašem planu',
      badge: 'Preporučeno',
      cards: [
        { name: 'Strateška konsultacija', price: '100 €', meta: '60 minuta', desc: 'Za konkretno pitanje, drugu procjenu ili odluku koju trebate donijeti sada.', bullets: ['Razgovor 1 na 1', 'Jasni naredni koraci'] },
        { name: 'Admissions Blueprint', price: '240 €', meta: 'fiksna cijena', desc: 'Procjena profila i pisani plan koji postavlja smjer cijelog procesa.', bullets: ['Analiza profila', 'Strateški razgovor', 'Pisani akcioni plan'] },
        { name: 'University Direction', price: 'od 490 €', meta: 'prema obimu', desc: 'Obrazložen uži izbor programa, rokova, budžeta i ključnih zahtjeva.', bullets: ['Strategija', 'Uži izbor programa', 'Mapa rokova i troškova'] },
        { name: 'Full Application Partnership', price: 'od 1.400 €', meta: 'prijavni ciklus', desc: 'Strukturirana podrška od strategije do finalne predaje dogovorenih prijava.', bullets: ['Plan i shortlist', 'CV i motivaciona pisma', 'Revizije i priprema intervjua'], featured: true },
      ],
    },
    process: {
      kicker: 'Kako radimo', phase: 'Faza',
      title: 'Jedan proces. Tri jasne faze.',
      steps: [
        ['Upoznajemo vašu polaznu tačku', 'Profil, interesi, budžet, rokovi i ograničenja — bez uljepšavanja i bez generičnih savjeta.'],
        ['Mapiramo realan put', 'Prioriteti, uži izbor i konkretan plan rada zasnovan na vašem cilju.'],
        ['Vodimo prijavu sa strukturom', 'Dajemo pitanja i iskren feedback; ideje, glas i konačne odluke ostaju vaši.'],
      ],
    },
    principles: {
      kicker: 'Boutique po izboru',
      title: 'Nismo prodajni kanal univerziteta.',
      body: 'Preporuke zasnivamo na vašem profilu, ciljevima, budžetu i rokovima. Ne obećavamo prijem; gradimo proces u kojem svaka odluka ima razlog.',
      labels: [['01', 'Nezavisna procjena'], ['02', 'Direktan rad sa savjetnikom'], ['03', 'Transparentan obim i cijena']],
      ethicsTitle: 'Vaša prijava ostaje vaša.',
      ethicsBody: 'Ne pišemo eseje umjesto kandidata i ne obećavamo prijem ili stipendiju. Dajemo strukturu, prava pitanja i povratne informacije kako biste svoju priču predstavili jasno i vjerodostojno.',
    },
    pricing: {
      kicker: 'Transparentne cijene',
      title: 'Znate okvir prije prvog plaćanja.',
      body: 'Kompletni angažmani se najčešće kreću između 1.400 i 2.500 €, zavisno od broja programa, stipendija i složenosti procesa.',
      table: [
        ['Uvodni fit razgovor', '15 min', '0 €'],
        ['Strateška konsultacija', '60 min', '100 €'],
        ['Profil i admissions strategija', 'od', '180 €'],
        ['Izbor univerziteta', 'od', '280 €'],
        ['Prva standardna prijava', 'od', '250 €'],
        ['Scholarship advisory', 'od', '200 €'],
        ['Priprema za intervju', 'od', '150 €'],
        ['Privatno mentorstvo', 'po satu', '110 €'],
      ],
      note: 'Stavke u tabeli su pojedinačne usluge; paketi iznad ih kombinuju po fiksnoj cijeni. Konačan obim usluge i cijenu potvrđujemo pisanim putem prije plaćanja.',
    },
    faq: {
      kicker: 'Česta pitanja',
      title: 'Prije nego rezervišete.',
      items: [
        ['Da li garantujete prijem ili stipendiju?', 'Ne. Odluku uvijek donosi univerzitet ili stipendijska komisija. Naš posao je da proces bude strateški, kvalitetan i autentičan.'],
        ['Da li radite bachelor i master prijave?', 'Da. Radimo s učenicima, studentima i porodicama koje ciljaju međunarodne bachelor i master programe, prvenstveno u Evropi.'],
        ['Pišete li motivaciona pisma umjesto kandidata?', 'Ne. Pomažemo da razvijete strukturu, argumente i vlastiti glas, a zatim dajemo detaljan feedback i revizije.'],
        ['Mogu li uzeti samo jednu uslugu?', 'Da. Možete početi konsultacijom, strategijom ili shortlistom bez obaveze da uzmete puni paket.'],
        ['Na kojem jeziku radimo?', 'Savjetovanje nudimo na bosanskom, srpskom, hrvatskom i engleskom. Za njemačko govorno područje dostupan je i njemački sadržaj.'],
        ['Šta uključuje besplatan razgovor?', 'Upoznajemo cilj, rokove i potrebe te provjeravamo da li smo dobar izbor. Ne uključuje detaljnu procjenu profila ili listu univerziteta.'],
      ],
    },
    booking: {
      kicker: 'Sljedeći korak',
      title: '15 minuta da vidimo postoji li dobar fit.',
      body: 'Besplatan razgovor služi da upoznamo vaše ciljeve, rokove i potrebe. Vaša vremenska zona prepoznaje se automatski.',
      event: 'Besplatan uvodni razgovor', duration: '15 minuta', location: 'Online · video poziv', timezone: 'Automatska vremenska zona',
      button: 'Otvori booking kalendar', pending: 'Cal.com kalendar spreman za povezivanje',
      paid: 'Za detaljnu procjenu profila rezervišite stratešku konsultaciju od 60 minuta.',
    },
    footer: {
      line: 'Clarity for every step.',
      description: 'Nezavisno savjetovanje za međunarodne prijave na studije.',
      rights: 'Sva prava zadržana.',
      email: 'kontakt@virela.com',
      legalLabel: 'Impresum',
      privacyLabel: 'Privatnost',
      legalEntity: 'Virela Admissions',
    },
  },
  sr: {
    localeName: 'Srpski',
    nav: { services: 'Usluge', process: 'Kako radimo', pricing: 'Cene', faq: 'Pitanja', book: 'Zakažite razgovor', language: 'Jezik' },
    hero: {
      eyebrow: 'Evropske prijave · Balkan i dijaspora',
      titleA: 'Prava prijava ne počinje formularom.',
      titleB: 'Počinje pravcem.',
      body: 'Individualno, nezavisno savetovanje za studije u inostranstvu — od izbora programa do prijave koja jasno predstavlja ko ste.',
      primary: 'Zakažite besplatan razgovor',
      secondary: 'Pogledajte usluge',
    },
    trust: ['Nezavisno savetovanje', 'Rad 1 na 1', 'Jasne cene'],
    route: {
      title: 'Vaša admissions ruta', live: 'jasno', next: 'Sledeći korak', free: '15 min · bez naknade',
      stops: [['PROFIL', 'Polazna tačka'], ['SMER', 'Pravi programi'], ['PRIJAVA', 'Jasna priča']],
      note: 'Ne biramo univerzitet umesto vas. Pomažemo da donesete bolju odluku.',
    },
    signals: {
      kicker: 'Pre prve prijave', title: 'Prvo mapiramo odluke koje zaista određuju ishod.',
      body: 'Dobra strategija povezuje akademski profil, finansije, rokove i ambiciju. Tek onda biramo programe i oblikujemo prijavu.',
      items: [
        ['Akademski fit', 'Procenjujemo gde je vaš profil konkurentan i gde treba ojačati priču.'],
        ['Budžet i stipendije', 'Troškove i realne izvore finansiranja uključujemo od prvog dana.'],
        ['Programi i zemlje', 'Ne pravimo generičku listu; svaki izbor mora imati jasan razlog.'],
        ['Rokovi i ritam', 'Kompleksan proces pretvaramo u prioritete, rokove i nedeljni plan.'],
      ],
    },
    services: {
      kicker: 'Usluge', title: 'Podrška onoliko široka koliko vam zaista treba.',
      body: 'Počnite jednom strateškom sesijom ili radite s nama kroz ceo prijavni ciklus.', cta: 'Razgovarajmo o vašem planu',
      badge: 'Preporučeno',
      cards: [
        { name: 'Strateška konsultacija', price: '100 €', meta: '60 minuta', desc: 'Za konkretno pitanje, drugo mišljenje ili odluku koju treba da donesete sada.', bullets: ['Razgovor 1 na 1', 'Jasni naredni koraci'] },
        { name: 'Admissions Blueprint', price: '240 €', meta: 'fiksna cena', desc: 'Procena profila i pisani plan koji postavlja smer celog procesa.', bullets: ['Analiza profila', 'Strateški razgovor', 'Pisani akcioni plan'] },
        { name: 'University Direction', price: 'od 490 €', meta: 'prema obimu', desc: 'Obrazložen uži izbor programa, rokova, budžeta i ključnih zahteva.', bullets: ['Strategija', 'Uži izbor programa', 'Mapa rokova i troškova'] },
        { name: 'Full Application Partnership', price: 'od 1.400 €', meta: 'prijavni ciklus', desc: 'Strukturirana podrška od strategije do finalne predaje dogovorenih prijava.', bullets: ['Plan i shortlist', 'CV i motivaciona pisma', 'Revizije i priprema intervjua'], featured: true },
      ],
    },
    process: {
      kicker: 'Kako radimo', phase: 'Faza', title: 'Jedan proces. Tri jasne faze.',
      steps: [
        ['Upoznajemo vašu polaznu tačku', 'Profil, interesovanja, budžet, rokovi i ograničenja — bez ulepšavanja i generičnih saveta.'],
        ['Mapiramo realan put', 'Prioriteti, uži izbor i konkretan plan rada zasnovan na vašem cilju.'],
        ['Vodimo prijavu sa strukturom', 'Dajemo pitanja i iskren feedback; ideje, glas i konačne odluke ostaju vaši.'],
      ],
    },
    principles: {
      kicker: 'Boutique po izboru', title: 'Nismo prodajni kanal univerziteta.',
      body: 'Preporuke zasnivamo na vašem profilu, ciljevima, budžetu i rokovima. Ne obećavamo prijem; gradimo proces u kojem svaka odluka ima razlog.',
      labels: [['01', 'Nezavisna procena'], ['02', 'Direktan rad sa savetnikom'], ['03', 'Transparentan obim i cena']],
      ethicsTitle: 'Vaša prijava ostaje vaša.',
      ethicsBody: 'Ne pišemo eseje umesto kandidata i ne obećavamo prijem ili stipendiju. Dajemo strukturu, prava pitanja i povratne informacije kako biste svoju priču predstavili jasno i autentično.',
    },
    pricing: {
      kicker: 'Transparentne cene', title: 'Znate okvir pre prvog plaćanja.',
      body: 'Kompletni angažmani se najčešće kreću između 1.400 i 2.500 €, zavisno od broja programa, stipendija i složenosti procesa.',
      table: [
        ['Uvodni fit razgovor', '15 min', '0 €'], ['Strateška konsultacija', '60 min', '100 €'],
        ['Profil i admissions strategija', 'od', '180 €'], ['Izbor univerziteta', 'od', '280 €'],
        ['Prva standardna prijava', 'od', '250 €'], ['Scholarship advisory', 'od', '200 €'],
        ['Priprema za intervju', 'od', '150 €'], ['Privatno mentorstvo', 'po satu', '110 €'],
      ],
      note: 'Stavke u tabeli su pojedinačne usluge; paketi iznad ih kombinuju po fiksnoj ceni. Konačan obim usluge i cenu potvrđujemo pisanim putem pre plaćanja.',
    },
    faq: {
      kicker: 'Česta pitanja', title: 'Pre nego što rezervišete.',
      items: [
        ['Da li garantujete prijem ili stipendiju?', 'Ne. Odluku uvek donosi univerzitet ili komisija. Naš posao je da proces bude strateški, kvalitetan i autentičan.'],
        ['Da li radite bachelor i master prijave?', 'Da. Radimo sa učenicima, studentima i porodicama koje ciljaju međunarodne bachelor i master programe, prvenstveno u Evropi.'],
        ['Pišete li motivaciona pisma umesto kandidata?', 'Ne. Pomažemo da razvijete strukturu, argumente i svoj glas, a zatim dajemo detaljan feedback i revizije.'],
        ['Mogu li uzeti samo jednu uslugu?', 'Da. Možete početi konsultacijom, strategijom ili shortlistom bez obaveze da uzmete puni paket.'],
        ['Na kom jeziku radimo?', 'Savetovanje nudimo na bosanskom, srpskom, hrvatskom i engleskom. Dostupan je i nemački sadržaj.'],
        ['Šta uključuje besplatan razgovor?', 'Upoznajemo cilj, rokove i potrebe i proveravamo da li smo dobar izbor. Ne uključuje detaljnu procenu profila ili listu univerziteta.'],
      ],
    },
    booking: {
      kicker: 'Sledeći korak', title: '15 minuta da vidimo postoji li dobar fit.',
      body: 'Besplatan razgovor služi da upoznamo vaše ciljeve, rokove i potrebe. Vaša vremenska zona prepoznaje se automatski.',
      event: 'Besplatan uvodni razgovor', duration: '15 minuta', location: 'Online · video poziv', timezone: 'Automatska vremenska zona',
      button: 'Otvori booking kalendar', pending: 'Cal.com kalendar spreman za povezivanje',
      paid: 'Za detaljnu procenu profila rezervišite stratešku konsultaciju od 60 minuta.',
    },
    footer: { line: 'Clarity for every step.', description: 'Nezavisno savetovanje za međunarodne prijave na studije.', rights: 'Sva prava zadržana.', email: 'kontakt@virela.com', legalLabel: 'Impresum', privacyLabel: 'Privatnost', legalEntity: 'Virela Admissions' },
  },
  hr: {
    localeName: 'Hrvatski',
    nav: { services: 'Usluge', process: 'Kako radimo', pricing: 'Cijene', faq: 'Pitanja', book: 'Rezervirajte razgovor', language: 'Jezik' },
    hero: {
      eyebrow: 'Europske prijave · Balkan i dijaspora', titleA: 'Prava prijava ne počinje obrascem.', titleB: 'Počinje smjerom.',
      body: 'Individualno, neovisno savjetovanje za studij u inozemstvu — od odabira programa do prijave koja jasno predstavlja tko ste.',
      primary: 'Rezervirajte besplatan razgovor', secondary: 'Pogledajte usluge',
    },
    trust: ['Neovisno savjetovanje', 'Osobna podrška', 'Jasne cijene'],
    route: {
      title: 'Vaša admissions ruta', live: 'jasno', next: 'Sljedeći korak', free: '15 min · bez naknade',
      stops: [['PROFIL', 'Polazna točka'], ['SMJER', 'Pravi programi'], ['PRIJAVA', 'Jasna priča']],
      note: 'Ne biramo studij umjesto vas. Pomažemo vam donijeti bolju odluku.',
    },
    signals: {
      kicker: 'Prije prve prijave', title: 'Prvo mapiramo odluke koje doista određuju ishod.',
      body: 'Dobra strategija povezuje akademski profil, financije, rokove i ambiciju. Tek onda biramo programe i oblikujemo prijavu.',
      items: [
        ['Akademski fit', 'Procjenjujemo gdje je vaš profil konkurentan i gdje treba ojačati priču.'],
        ['Budžet i stipendije', 'Troškove i realne izvore financiranja uključujemo od prvog dana.'],
        ['Programi i zemlje', 'Ne radimo generičku listu; svaki odabir mora imati jasan razlog.'],
        ['Rokovi i ritam', 'Složen proces pretvaramo u prioritete, rokove i tjedni plan.'],
      ],
    },
    services: {
      kicker: 'Usluge', title: 'Podrška onoliko široka koliko vam doista treba.',
      body: 'Počnite jednom strateškom sesijom ili radite s nama kroz cijeli prijavni ciklus.', cta: 'Razgovarajmo o vašem planu',
      badge: 'Preporučeno',
      cards: [
        { name: 'Strateško savjetovanje', price: '100 €', meta: '60 minuta', desc: 'Za konkretno pitanje, drugo mišljenje ili odluku koju trebate donijeti sada.', bullets: ['Razgovor 1 na 1', 'Jasni sljedeći koraci'] },
        { name: 'Admissions Blueprint', price: '240 €', meta: 'fiksna cijena', desc: 'Procjena profila i pisani plan koji postavlja smjer cijelog procesa.', bullets: ['Analiza profila', 'Strateški razgovor', 'Pisani akcijski plan'] },
        { name: 'University Direction', price: 'od 490 €', meta: 'prema opsegu', desc: 'Obrazložen uži izbor studija, rokova, budžeta i ključnih zahtjeva.', bullets: ['Strategija', 'Uži izbor studija', 'Mapa rokova i troškova'] },
        { name: 'Full Application Partnership', price: 'od 1.400 €', meta: 'prijavni ciklus', desc: 'Strukturirana podrška od strategije do konačne predaje dogovorenih prijava.', bullets: ['Plan i shortlist', 'CV i motivacijska pisma', 'Revizije i priprema intervjua'], featured: true },
      ],
    },
    process: {
      kicker: 'Kako radimo', phase: 'Faza', title: 'Jedan proces. Tri jasne faze.',
      steps: [
        ['Upoznajemo vašu polaznu točku', 'Profil, interesi, budžet, rokovi i ograničenja — bez uljepšavanja i generičkih savjeta.'],
        ['Mapiramo realan put', 'Prioriteti, uži izbor i konkretan plan rada zasnovan na vašem cilju.'],
        ['Vodimo prijavu sa strukturom', 'Dajemo pitanja i iskren feedback; ideje, glas i konačne odluke ostaju vaši.'],
      ],
    },
    principles: {
      kicker: 'Boutique po izboru', title: 'Nismo prodajni kanal sveučilišta.',
      body: 'Preporuke zasnivamo na vašem profilu, ciljevima, budžetu i rokovima. Ne obećavamo upis; gradimo proces u kojem svaka odluka ima razlog.',
      labels: [['01', 'Neovisna procjena'], ['02', 'Izravan rad sa savjetnikom'], ['03', 'Transparentan opseg i cijena']],
      ethicsTitle: 'Vaša prijava ostaje vaša.',
      ethicsBody: 'Ne pišemo eseje umjesto kandidata i ne obećavamo upis ili stipendiju. Dajemo strukturu, prava pitanja i povratne informacije kako biste svoju priču predstavili jasno i autentično.',
    },
    pricing: {
      kicker: 'Transparentne cijene', title: 'Znate okvir prije prvog plaćanja.',
      body: 'Cjeloviti angažmani najčešće se kreću između 1.400 i 2.500 €, ovisno o broju programa, stipendija i složenosti procesa.',
      table: [
        ['Uvodni fit razgovor', '15 min', '0 €'], ['Strateško savjetovanje', '60 min', '100 €'],
        ['Profil i admissions strategija', 'od', '180 €'], ['Odabir sveučilišta', 'od', '280 €'],
        ['Prva standardna prijava', 'od', '250 €'], ['Savjetovanje za stipendije', 'od', '200 €'],
        ['Priprema za intervju', 'od', '150 €'], ['Privatno mentorstvo', 'po satu', '110 €'],
      ],
      note: 'Stavke u tablici su pojedinačne usluge; paketi iznad ih kombiniraju po fiksnoj cijeni. Konačan opseg usluge i cijenu potvrđujemo pisanim putem prije plaćanja.',
    },
    faq: {
      kicker: 'Česta pitanja', title: 'Prije nego rezervirate.',
      items: [
        ['Jamčite li upis ili stipendiju?', 'Ne. Odluku uvijek donosi sveučilište ili komisija. Naš je posao da proces bude strateški, kvalitetan i autentičan.'],
        ['Radite li bachelor i master prijave?', 'Da. Radimo s učenicima, studentima i obiteljima koje ciljaju međunarodne bachelor i master programe, prvenstveno u Europi.'],
        ['Pišete li motivacijska pisma umjesto kandidata?', 'Ne. Pomažemo vam razviti strukturu, argumente i vlastiti glas, a zatim dajemo detaljan feedback i revizije.'],
        ['Mogu li uzeti samo jednu uslugu?', 'Da. Možete početi savjetovanjem, strategijom ili shortlistom bez obveze da uzmete puni paket.'],
        ['Na kojem jeziku radimo?', 'Savjetovanje nudimo na bosanskom, srpskom, hrvatskom i engleskom. Dostupan je i njemački sadržaj.'],
        ['Što uključuje besplatan razgovor?', 'Upoznajemo cilj, rokove i potrebe te provjeravamo odgovaramo li vam. Ne uključuje detaljnu procjenu profila ili listu sveučilišta.'],
      ],
    },
    booking: {
      kicker: 'Sljedeći korak', title: '15 minuta da vidimo postoji li dobar fit.',
      body: 'Besplatan razgovor služi da upoznamo vaše ciljeve, rokove i potrebe. Vaša vremenska zona prepoznaje se automatski.',
      event: 'Besplatan uvodni razgovor', duration: '15 minuta', location: 'Online · video poziv', timezone: 'Automatska vremenska zona',
      button: 'Otvori booking kalendar', pending: 'Cal.com kalendar spreman za povezivanje',
      paid: 'Za detaljnu procjenu profila rezervirajte strateško savjetovanje od 60 minuta.',
    },
    footer: { line: 'Clarity for every step.', description: 'Neovisno savjetovanje za međunarodne prijave na studij.', rights: 'Sva prava pridržana.', email: 'kontakt@virela.com', legalLabel: 'Impresum', privacyLabel: 'Privatnost', legalEntity: 'Virela Admissions' },
  },
  en: {
    localeName: 'English',
    nav: { services: 'Services', process: 'How it works', pricing: 'Pricing', faq: 'FAQ', book: 'Book a call', language: 'Language' },
    hero: {
      eyebrow: 'European admissions · Balkans & diaspora', titleA: 'A strong application does not start with a form.', titleB: 'It starts with direction.',
      body: 'Independent, one-to-one guidance for studying abroad—from choosing the right programs to submitting an application that clearly represents who you are.',
      primary: 'Book a free introductory call', secondary: 'Explore services',
    },
    trust: ['Independent guidance', 'One-to-one support', 'Transparent pricing'],
    route: {
      title: 'Your admissions route', live: 'clear', next: 'Next step', free: '15 min · complimentary',
      stops: [['PROFILE', 'Starting point'], ['DIRECTION', 'Right programs'], ['APPLICATION', 'A clear story']],
      note: 'We do not choose a university for you. We help you make a better decision.',
    },
    signals: {
      kicker: 'Before the first application', title: 'First, we map the decisions that actually shape the outcome.',
      body: 'A sound strategy connects academic fit, finances, deadlines and ambition. Only then do we choose programs and shape the application.',
      items: [
        ['Academic fit', 'We assess where your profile is competitive and where your story needs work.'],
        ['Budget & funding', 'Costs and realistic sources of funding enter the plan from day one.'],
        ['Programs & countries', 'No generic lists; every recommendation needs a clear reason.'],
        ['Deadlines & pace', 'We turn a complex process into priorities, deadlines and a weekly rhythm.'],
      ],
    },
    services: {
      kicker: 'Services', title: 'Support as focused—or as complete—as you need.',
      body: 'Start with one strategic session or work with us throughout the application cycle.', cta: 'Discuss your plan',
      badge: 'Recommended',
      cards: [
        { name: 'Strategy Consultation', price: '€100', meta: '60 minutes', desc: 'For a concrete question, a second opinion or a decision you need to make now.', bullets: ['One-to-one session', 'Clear next steps'] },
        { name: 'Admissions Blueprint', price: '€240', meta: 'fixed price', desc: 'A profile assessment and written plan that sets the direction for the process.', bullets: ['Profile analysis', 'Strategy session', 'Written action plan'] },
        { name: 'University Direction', price: 'from €490', meta: 'scope-based', desc: 'A reasoned shortlist with deadlines, costs and key requirements mapped out.', bullets: ['Strategy', 'Program shortlist', 'Deadline & cost map'] },
        { name: 'Full Application Partnership', price: 'from €1,400', meta: 'application cycle', desc: 'Structured support from initial strategy through submission of the agreed applications.', bullets: ['Plan & shortlist', 'CV and written materials', 'Reviews & interview prep'], featured: true },
      ],
    },
    process: {
      kicker: 'How it works', phase: 'Phase', title: 'One process. Three clear phases.',
      steps: [
        ['Understand your starting point', 'Your profile, interests, budget, deadlines and constraints—with candour and without generic advice.'],
        ['Map a realistic route', 'Priorities, a reasoned shortlist and a concrete work plan built around your goal.'],
        ['Apply with structure', 'We ask the right questions and give honest feedback; the ideas, voice and final decisions remain yours.'],
      ],
    },
    principles: {
      kicker: 'Boutique by design', title: 'We are not a university sales channel.',
      body: 'Recommendations are based on your profile, goals, budget and deadlines. We do not promise admission; we build a process where every choice has a reason.',
      labels: [['01', 'Independent assessment'], ['02', 'Direct adviser access'], ['03', 'Transparent scope & fees']],
      ethicsTitle: 'Your application remains yours.',
      ethicsBody: 'We do not write essays for applicants or promise admission or scholarships. We provide structure, the right questions and detailed feedback so you can present your own story clearly and authentically.',
    },
    pricing: {
      kicker: 'Transparent pricing', title: 'Know the range before you pay.',
      body: 'Complete engagements typically range from €1,400 to €2,500, depending on the number of programs, scholarship work and complexity.',
      table: [
        ['Introductory fit call', '15 min', '€0'], ['Strategy Consultation', '60 min', '€100'],
        ['Profile & admissions strategy', 'from', '€180'], ['University selection', 'from', '€280'],
        ['First standard application', 'from', '€250'], ['Scholarship advisory', 'from', '€200'],
        ['Interview preparation', 'from', '€150'], ['Private mentoring', 'per hour', '€110'],
      ],
      note: 'The table lists individual services; the packages above bundle them at a set price. We confirm the final scope and fee in writing before payment.',
    },
    faq: {
      kicker: 'Frequently asked', title: 'Before you book.',
      items: [
        ['Do you guarantee admission or scholarships?', 'No. The university or scholarship committee always makes that decision. Our role is to make the process strategic, rigorous and authentic.'],
        ['Do you support bachelor’s and master’s applicants?', 'Yes. We work with students and families targeting international bachelor’s and master’s programs, primarily across Europe.'],
        ['Do you write motivation letters for applicants?', 'No. We help you develop structure, arguments and your own voice, then provide detailed feedback and revisions.'],
        ['Can I purchase just one service?', 'Yes. You can start with a consultation, strategy or shortlist without committing to a full package.'],
        ['Which languages do you work in?', 'Guidance is available in Bosnian, Serbian, Croatian and English. German-language site content is also available.'],
        ['What happens in the free call?', 'We learn about your goals, timeline and needs and assess mutual fit. It does not include a detailed profile review or university shortlist.'],
      ],
    },
    booking: {
      kicker: 'Your next step', title: '15 minutes to see if the fit is right.',
      body: 'The free call helps us understand your goals, timeline and needs. Your time zone is detected automatically.',
      event: 'Free introductory call', duration: '15 minutes', location: 'Online · video call', timezone: 'Automatic time zone',
      button: 'Open booking calendar', pending: 'Cal.com calendar ready to connect',
      paid: 'For a detailed profile review, book a 60-minute strategy consultation.',
    },
    footer: { line: 'Clarity for every step.', description: 'Independent guidance for international university applications.', rights: 'All rights reserved.', email: 'kontakt@virela.com', legalLabel: 'Legal notice', privacyLabel: 'Privacy', legalEntity: 'Virela Admissions' },
  },
  de: {
    localeName: 'Deutsch',
    nav: { services: 'Leistungen', process: 'Ablauf', pricing: 'Preise', faq: 'FAQ', book: 'Gespräch buchen', language: 'Sprache' },
    hero: {
      eyebrow: 'Europäische Bewerbungen · Balkan & Diaspora', titleA: 'Eine starke Bewerbung beginnt nicht mit einem Formular.', titleB: 'Sie beginnt mit Orientierung.',
      body: 'Unabhängige, persönliche Beratung für ein Studium im Ausland – von der Auswahl passender Programme bis zu einer Bewerbung, die Sie klar und authentisch zeigt.',
      primary: 'Kostenloses Kennenlerngespräch', secondary: 'Leistungen ansehen',
    },
    trust: ['Unabhängige Beratung', 'Persönliche Begleitung', 'Transparente Preise'],
    route: {
      title: 'Ihr Bewerbungsweg', live: 'klar', next: 'Nächster Schritt', free: '15 Min. · kostenlos',
      stops: [['PROFIL', 'Ausgangslage'], ['RICHTUNG', 'Passende Programme'], ['BEWERBUNG', 'Eine klare Geschichte']],
      note: 'Wir wählen keine Universität für Sie. Wir helfen Ihnen, besser zu entscheiden.',
    },
    signals: {
      kicker: 'Vor der ersten Bewerbung', title: 'Zuerst planen wir die Entscheidungen, die wirklich zählen.',
      body: 'Eine gute Strategie verbindet akademische Eignung, Finanzen, Fristen und Ambition. Erst dann wählen wir Programme und entwickeln die Bewerbung.',
      items: [
        ['Akademische Eignung', 'Wir prüfen, wo Ihr Profil konkurrenzfähig ist und wo Ihre Geschichte geschärft werden muss.'],
        ['Budget & Förderung', 'Kosten und realistische Finanzierungsmöglichkeiten fließen von Anfang an ein.'],
        ['Programme & Länder', 'Keine generischen Listen; jede Empfehlung braucht einen klaren Grund.'],
        ['Fristen & Tempo', 'Wir übersetzen einen komplexen Prozess in Prioritäten, Termine und einen Wochenrhythmus.'],
      ],
    },
    services: {
      kicker: 'Leistungen', title: 'So fokussiert oder umfassend, wie Sie es benötigen.',
      body: 'Starten Sie mit einer Strategiesitzung oder arbeiten Sie mit uns durch den gesamten Bewerbungszyklus.', cta: 'Plan besprechen',
      badge: 'Empfohlen',
      cards: [
        { name: 'Strategieberatung', price: '100 €', meta: '60 Minuten', desc: 'Für eine konkrete Frage, eine zweite Einschätzung oder eine anstehende Entscheidung.', bullets: ['Persönliches Gespräch', 'Klare nächste Schritte'] },
        { name: 'Admissions Blueprint', price: '240 €', meta: 'Festpreis', desc: 'Profilanalyse und schriftlicher Plan als Richtung für den gesamten Prozess.', bullets: ['Profilanalyse', 'Strategiegespräch', 'Schriftlicher Aktionsplan'] },
        { name: 'University Direction', price: 'ab 490 €', meta: 'nach Umfang', desc: 'Begründete Programmauswahl mit Fristen, Kosten und Anforderungen.', bullets: ['Strategie', 'Programmauswahl', 'Fristen- und Kostenplan'] },
        { name: 'Full Application Partnership', price: 'ab 1.400 €', meta: 'Bewerbungszyklus', desc: 'Strukturierte Begleitung von der Strategie bis zur Einreichung der vereinbarten Bewerbungen.', bullets: ['Plan & Shortlist', 'Lebenslauf und Texte', 'Feedback & Interviewtraining'], featured: true },
      ],
    },
    process: {
      kicker: 'So arbeiten wir', phase: 'Phase', title: 'Ein Prozess. Drei klare Phasen.',
      steps: [
        ['Ausgangslage verstehen', 'Profil, Interessen, Budget, Fristen und Grenzen – ehrlich und ohne allgemeine Standardtipps.'],
        ['Einen realistischen Weg planen', 'Prioritäten, eine begründete Auswahl und ein konkreter Arbeitsplan für Ihr Ziel.'],
        ['Strukturiert bewerben', 'Wir stellen die richtigen Fragen und geben ehrliches Feedback; Ideen, Stimme und Entscheidungen bleiben Ihre.'],
      ],
    },
    principles: {
      kicker: 'Bewusst persönlich', title: 'Wir sind kein Vertriebskanal für Universitäten.',
      body: 'Unsere Empfehlungen basieren auf Ihrem Profil, Ihren Zielen, Ihrem Budget und Ihren Fristen. Wir versprechen keine Zulassung; wir schaffen einen Prozess, in dem jede Entscheidung begründet ist.',
      labels: [['01', 'Unabhängige Einschätzung'], ['02', 'Direkter Beraterkontakt'], ['03', 'Transparenter Umfang & Preis']],
      ethicsTitle: 'Ihre Bewerbung bleibt Ihre eigene.',
      ethicsBody: 'Wir schreiben keine Essays für Bewerber:innen und versprechen weder Zulassung noch Stipendien. Wir geben Struktur, stellen die richtigen Fragen und liefern detailliertes Feedback, damit Sie Ihre Geschichte klar und authentisch darstellen können.',
    },
    pricing: {
      kicker: 'Transparente Preise', title: 'Kennen Sie den Rahmen vor der Zahlung.',
      body: 'Komplette Begleitungen liegen meist zwischen 1.400 und 2.500 €, abhängig von Programmanzahl, Stipendienarbeit und Komplexität.',
      table: [
        ['Kennenlerngespräch', '15 Min.', '0 €'], ['Strategieberatung', '60 Min.', '100 €'],
        ['Profil- & Bewerbungsstrategie', 'ab', '180 €'], ['Hochschulauswahl', 'ab', '280 €'],
        ['Erste Standardbewerbung', 'ab', '250 €'], ['Stipendienberatung', 'ab', '200 €'],
        ['Interviewvorbereitung', 'ab', '150 €'], ['Persönliches Mentoring', 'pro Std.', '110 €'],
      ],
      note: 'Die Tabelle listet Einzelleistungen; die Pakete oben bündeln sie zu einem Festpreis. Den endgültigen Umfang und Preis bestätigen wir vor der Zahlung schriftlich.',
    },
    faq: {
      kicker: 'Häufige Fragen', title: 'Bevor Sie buchen.',
      items: [
        ['Garantieren Sie eine Zulassung oder ein Stipendium?', 'Nein. Die Entscheidung trifft immer die Universität oder die Stipendienkommission. Wir sorgen für einen strategischen, sorgfältigen und authentischen Prozess.'],
        ['Begleiten Sie Bachelor- und Masterbewerbungen?', 'Ja. Wir arbeiten mit Schüler:innen, Studierenden und Familien für internationale Bachelor- und Masterprogramme, vor allem in Europa.'],
        ['Schreiben Sie Motivationsschreiben für Bewerber:innen?', 'Nein. Wir helfen bei Struktur, Argumenten und der eigenen Stimme und geben anschließend detailliertes Feedback.'],
        ['Kann ich nur eine einzelne Leistung buchen?', 'Ja. Sie können mit einer Beratung, Strategie oder Auswahl starten, ohne ein Gesamtpaket zu buchen.'],
        ['In welchen Sprachen beraten Sie?', 'Beratung ist auf Bosnisch, Serbisch, Kroatisch und Englisch möglich. Deutsche Website-Inhalte sind ebenfalls verfügbar.'],
        ['Was beinhaltet das kostenlose Gespräch?', 'Wir lernen Ziele, Zeitplan und Bedarf kennen und prüfen die Zusammenarbeit. Eine ausführliche Profilanalyse oder Hochschulliste ist nicht enthalten.'],
      ],
    },
    booking: {
      kicker: 'Nächster Schritt', title: '15 Minuten, um die Zusammenarbeit zu prüfen.',
      body: 'Im kostenlosen Gespräch lernen wir Ihre Ziele, Ihren Zeitplan und Ihren Beratungsbedarf kennen. Ihre Zeitzone wird automatisch erkannt.',
      event: 'Kostenloses Kennenlerngespräch', duration: '15 Minuten', location: 'Online · Videoanruf', timezone: 'Automatische Zeitzone',
      button: 'Buchungskalender öffnen', pending: 'Cal.com-Kalender bereit zur Verbindung',
      paid: 'Für eine ausführliche Profilanalyse buchen Sie eine 60-minütige Strategieberatung.',
    },
    footer: { line: 'Klarheit bei jedem Schritt.', description: 'Unabhängige Beratung für internationale Hochschulbewerbungen.', rights: 'Alle Rechte vorbehalten.', email: 'kontakt@virela.com', legalLabel: 'Impressum', privacyLabel: 'Datenschutz', legalEntity: 'Virela Admissions' },
  },
} as const;

export type Locale = keyof typeof translations;
