export const translations = {
  bs: {
    localeName: 'Bosanski',
    nav: { services: 'Usluge', process: 'Kako radimo', pricing: 'Cijene', faq: 'Pitanja', book: 'Zakažite razgovor' },
    hero: {
      eyebrow: 'Prijave na evropske univerzitete · savjetovanje na vašem jeziku',
      titleA: 'Studirajte u inostranstvu.',
      titleB: 'Prijavite se s jasnim planom.',
      body: 'Zajedno pretvaramo izbor programa, troškove, stipendije i rokove u jasan plan za bachelor ili master prijavu.',
      primary: 'Razjasnite sljedeći korak — 15 min besplatno',
      secondary: 'Pogledajte kako radimo',
    },
    trust: ['Nezavisno savjetovanje', 'Rad 1 na 1', 'Jasne cijene'],
    route: {
      title: 'Vaša admissions ruta', live: 'jasno', next: 'Sljedeći korak', free: '15 min · bez naknade',
      stops: [['PROFIL', 'Polazna tačka'], ['SMJER', 'Pravi programi'], ['PRIJAVA', 'Jasna priča']],
      note: 'Zajedno biramo smjer koji najbolje odgovara vašem cilju.',
    },
    signals: {
      kicker: 'Prije prve prijave',
      title: 'Prvo razjasnimo odluke koje grade dobru prijavu.',
      body: 'Profil, budžet, rokovi i ambicija postaju jedan izvediv plan.',
      items: [
        ['Akademski fit', 'Prepoznajemo gdje ste najjači i kako to jasno pokazati.'],
        ['Budžet i stipendije', 'Od početka povezujemo troškove s dostupnim izvorima finansiranja.'],
        ['Programi i zemlje', 'Svaki program u užem izboru ima jasan razlog.'],
        ['Rokovi i ritam', 'Postavljamo prioritete, rokove i sedmični ritam.'],
      ],
    },
    services: {
      kicker: 'Usluge',
      title: 'Podrška onoliko široka koliko vam zaista treba.',
      body: 'Počnite jednom strateškom sesijom ili radite s nama kroz cijeli prijavni ciklus.',
      cta: 'Razgovarajmo o vašem planu',
      cards: [
        { name: 'Strateška konsultacija', price: '100 €', meta: '60 minuta', desc: 'Za konkretno pitanje, drugu procjenu ili odluku koju trebate donijeti sada.', bullets: ['Razgovor 1 na 1', 'Jasni naredni koraci'] },
        { name: 'Admissions Blueprint', price: '240 €', meta: 'fiksna cijena', desc: 'Procjena profila i pisani plan koji postavlja smjer cijelog procesa.', bullets: ['Ulazna analiza profila', 'Strateški razgovor od 60 minuta', 'Pisani plan u roku od 5 radnih dana'] },
        { name: 'University Direction', price: 'od 490 €', meta: 'prema obimu', desc: 'Obrazložen uži izbor programa, rokova, budžeta i ključnih zahtjeva.', bullets: ['Do 8 programa', 'Mapa rokova i troškova', 'Jedna revizija'] },
        { name: 'Full Application Partnership', price: '1.400–2.500 €', meta: 'prijavni ciklus', desc: 'Do četiri evropska programa; dodatne, stipendijske i zahtjevnije UK/US prijave posebno se ugovaraju.', bullets: ['Plan i shortlist', 'Dvije revizije po dogovorenom dokumentu', 'Unaprijed definisan period podrške'], featured: true },
      ],
    },
    process: {
      kicker: 'Kako radimo',
      title: 'Jedan proces. Tri jasne faze.',
      steps: [
        ['Upoznajemo vas', 'Vaši interesi, iskustvo, budžet i rokovi.'],
        ['Gradimo realan plan', 'Prioriteti, uži izbor i konkretan ritam rada.'],
        ['Zajedno jačamo prijavu', 'Prava pitanja i iskren feedback pomažu da vaš glas dođe do izražaja.'],
      ],
    },
    principles: {
      kicker: 'Boutique po izboru',
      title: 'Vaš interes vodi svaku preporuku.',
      body: 'Svaki izbor provjeravamo prema akademskoj usklađenosti, trošku, rokovima, finansiranju i realnim izgledima.',
      labels: [['01', 'Vaš interes na prvom mjestu'], ['02', 'Direktan rad sa savjetnikom'], ['03', 'Jasan obim i cijena']],
      ethicsTitle: 'Vaš glas. Naša puna podrška.',
      ethicsBody: 'Maksimalno se trudimo da vaša prijava bude snažna, lična i vjerodostojna. Vi zadržavate svoj glas; mi donosimo strukturu, prava pitanja i precizan feedback.',
    },
    pricing: {
      kicker: 'Transparentne cijene',
      title: 'Znate okvir prije prvog plaćanja.',
      body: 'Kompletni angažmani se najčešće kreću između 1.400 i 2.500 €, zavisno od broja programa, stipendija i složenosti procesa.',
      table: [
        ['Uvodni fit razgovor', '15 min', '0 €'],
        ['Ekspertska konsultacija', '60 min', '100 €'],
        ['Admissions Blueprint', 'fiksno', '240 €'],
        ['University Direction', 'od', '490 €'],
        ['Prva standardna prijava', 'od', '250 €'],
        ['Scholarship advisory', 'od', '200 €'],
        ['Priprema za intervju', 'od', '150 €'],
        ['Privatno mentorstvo', 'po satu', '110 €'],
      ],
      note: 'Konačan obim usluge i cijenu potvrđujemo pisanim putem prije plaćanja.',
    },
    faq: {
      kicker: 'Česta pitanja',
      title: 'Sve što trebate znati.',
      items: [
        ['Kako pomažete kandidatu da napravi što snažniju prijavu?', 'Svaku prijavu usmjeravamo prema kriterijima konkretnog programa. Zajedno gradimo strategiju, argumente, dokumente i pripremu za intervju, uz iskustvo s DAAD, Erasmus Mundus, OeAD i France Excellence stipendijama.'],
        ['Da li radite bachelor i master prijave?', 'Da. Radimo s učenicima, studentima i porodicama koje ciljaju međunarodne bachelor i master programe, prvenstveno u Evropi.'],
        ['Kako radimo na motivacionom pismu?', 'Vi zadržavate svoj glas, a mi pomažemo sa strukturom, argumentima, detaljnim feedbackom i revizijama.'],
        ['Mogu li uzeti samo jednu uslugu?', 'Da. Počnite konsultacijom, strategijom ili shortlistom — onim što vam sada najviše koristi.'],
        ['Na kojem jeziku radimo?', 'Savjetovanje i sadržaj nudimo na bosanskom, hrvatskom, srpskom/crnogorskom, engleskom, njemačkom i francuskom.'],
        ['Šta uključuje besplatan razgovor?', 'U 15 minuta upoznajemo vaš cilj, rokove i potrebe te dogovaramo najbolji sljedeći korak.'],
      ],
    },
    booking: {
      kicker: 'Sljedeći korak',
      title: '15 minuta za jasan sljedeći korak.',
      body: 'Odaberite termin, a mi ćemo upoznati vaš cilj, rokove i potrebe.',
      event: 'Besplatan uvodni razgovor', duration: '15 minuta', location: 'Online · video poziv', timezone: 'Automatska vremenska zona',
      button: 'Otvori booking kalendar', pending: 'Booking kalendar spreman za povezivanje',
      paid: 'Za potpunu strategiju odaberite konsultaciju od 60 minuta.',
    },
    footer: {
      line: 'Clarity for every step.',
      description: 'Lična podrška za snažnije međunarodne prijave na studije.',
      rights: 'Sva prava zadržana.',
    },
  },
  sr: {
    localeName: 'Srpski',
    nav: { services: 'Usluge', process: 'Kako radimo', pricing: 'Cene', faq: 'Pitanja', book: 'Zakažite razgovor' },
    hero: {
      eyebrow: 'Prijave na evropske univerzitete · savetovanje na vašem jeziku',
      titleA: 'Studirajte u inostranstvu.',
      titleB: 'Prijavite se sa jasnim planom.',
      body: 'Zajedno pretvaramo izbor programa, troškove, stipendije i rokove u jasan plan za osnovne ili master studije.',
      primary: 'Razjasnite sledeći korak — 15 min besplatno',
      secondary: 'Pogledajte kako radimo',
    },
    trust: ['Nezavisno savetovanje', 'Rad 1 na 1', 'Jasne cene'],
    route: {
      title: 'Vaša admissions ruta', live: 'jasno', next: 'Sledeći korak', free: '15 min · bez naknade',
      stops: [['PROFIL', 'Polazna tačka'], ['SMER', 'Pravi programi'], ['PRIJAVA', 'Jasna priča']],
      note: 'Zajedno biramo smer koji najbolje odgovara vašem cilju.',
    },
    signals: {
      kicker: 'Pre prve prijave', title: 'Prvo razjasnimo odluke koje grade dobru prijavu.',
      body: 'Profil, budžet, rokovi i ambicija postaju jedan ostvariv plan.',
      items: [
        ['Akademski fit', 'Prepoznajemo gde ste najjači i kako to jasno pokazati.'],
        ['Budžet i stipendije', 'Od početka povezujemo troškove s dostupnim izvorima finansiranja.'],
        ['Programi i zemlje', 'Svaki program u užem izboru ima jasan razlog.'],
        ['Rokovi i ritam', 'Postavljamo prioritete, rokove i nedeljni ritam.'],
      ],
    },
    services: {
      kicker: 'Usluge', title: 'Podrška onoliko široka koliko vam zaista treba.',
      body: 'Počnite jednom strateškom sesijom ili radite s nama kroz ceo prijavni ciklus.', cta: 'Razgovarajmo o vašem planu',
      cards: [
        { name: 'Strateška konsultacija', price: '100 €', meta: '60 minuta', desc: 'Za konkretno pitanje, drugo mišljenje ili odluku koju treba da donesete sada.', bullets: ['Razgovor 1 na 1', 'Jasni naredni koraci'] },
        { name: 'Admissions Blueprint', price: '240 €', meta: 'fiksna cena', desc: 'Procena profila i pisani plan koji postavlja smer celog procesa.', bullets: ['Ulazna analiza profila', 'Strateški razgovor od 60 minuta', 'Pisani plan u roku od 5 radnih dana'] },
        { name: 'University Direction', price: 'od 490 €', meta: 'prema obimu', desc: 'Obrazložen uži izbor programa, rokova, budžeta i ključnih zahteva.', bullets: ['Do 8 programa', 'Mapa rokova i troškova', 'Jedna revizija'] },
        { name: 'Full Application Partnership', price: '1.400–2.500 €', meta: 'prijavni ciklus', desc: 'Do četiri evropska programa; dodatne, stipendijske i zahtevnije UK/US prijave posebno se ugovaraju.', bullets: ['Plan i shortlist', 'Dve revizije po dogovorenom dokumentu', 'Unapred definisan period podrške'], featured: true },
      ],
    },
    process: {
      kicker: 'Kako radimo', title: 'Jedan proces. Tri jasne faze.',
      steps: [
        ['Upoznajemo vas', 'Vaša interesovanja, iskustvo, budžet i rokovi.'],
        ['Gradimo realan plan', 'Prioriteti, uži izbor i konkretan ritam rada.'],
        ['Zajedno jačamo prijavu', 'Prava pitanja i iskren feedback pomažu da vaš glas dođe do izražaja.'],
      ],
    },
    principles: {
      kicker: 'Boutique po izboru', title: 'Vaš interes vodi svaku preporuku.',
      body: 'Svaki izbor proveravamo prema akademskoj usklađenosti, trošku, rokovima, finansiranju i realnim izgledima.',
      labels: [['01', 'Vaš interes na prvom mestu'], ['02', 'Direktan rad sa savetnikom'], ['03', 'Jasan obim i cena']],
      ethicsTitle: 'Vaš glas. Naša puna podrška.',
      ethicsBody: 'Maksimalno se trudimo da vaša prijava bude snažna, lična i verodostojna. Vi zadržavate svoj glas; mi donosimo strukturu, prava pitanja i precizan feedback.',
    },
    pricing: {
      kicker: 'Transparentne cene', title: 'Znate okvir pre prvog plaćanja.',
      body: 'Kompletni angažmani se najčešće kreću između 1.400 i 2.500 €, zavisno od broja programa, stipendija i složenosti procesa.',
      table: [
        ['Uvodni fit razgovor', '15 min', '0 €'], ['Ekspertska konsultacija', '60 min', '100 €'],
        ['Admissions Blueprint', 'fiksno', '240 €'], ['University Direction', 'od', '490 €'],
        ['Prva standardna prijava', 'od', '250 €'], ['Scholarship advisory', 'od', '200 €'],
        ['Priprema za intervju', 'od', '150 €'], ['Privatno mentorstvo', 'po satu', '110 €'],
      ],
      note: 'Konačan obim usluge i cenu potvrđujemo pisanim putem pre plaćanja.',
    },
    faq: {
      kicker: 'Česta pitanja', title: 'Sve što treba da znate.',
      items: [
        ['Kako pomažete kandidatu da napravi što snažniju prijavu?', 'Svaku prijavu usmeravamo prema kriterijumima konkretnog programa. Zajedno gradimo strategiju, argumente, dokumente i pripremu za intervju, uz iskustvo sa DAAD, Erasmus Mundus, OeAD i France Excellence stipendijama.'],
        ['Da li radite bachelor i master prijave?', 'Da. Radimo sa učenicima, studentima i porodicama koje ciljaju međunarodne bachelor i master programe, prvenstveno u Evropi.'],
        ['Kako radimo na motivacionom pismu?', 'Vi zadržavate svoj glas, a mi pomažemo sa strukturom, argumentima, detaljnim feedbackom i revizijama.'],
        ['Mogu li uzeti samo jednu uslugu?', 'Da. Počnite konsultacijom, strategijom ili shortlistom — onim što vam sada najviše koristi.'],
        ['Na kom jeziku radimo?', 'Savetovanje i sadržaj nudimo na bosanskom, hrvatskom, srpskom/crnogorskom, engleskom, nemačkom i francuskom.'],
        ['Šta uključuje besplatan razgovor?', 'U 15 minuta upoznajemo vaš cilj, rokove i potrebe i dogovaramo najbolji sledeći korak.'],
      ],
    },
    booking: {
      kicker: 'Sledeći korak', title: '15 minuta za jasan sledeći korak.',
      body: 'Izaberite termin, a mi ćemo upoznati vaš cilj, rokove i potrebe.',
      event: 'Besplatan uvodni razgovor', duration: '15 minuta', location: 'Online · video poziv', timezone: 'Automatska vremenska zona',
      button: 'Otvori booking kalendar', pending: 'Booking kalendar spreman za povezivanje',
      paid: 'Za potpunu strategiju izaberite konsultaciju od 60 minuta.',
    },
    footer: { line: 'Clarity for every step.', description: 'Lična podrška za snažnije međunarodne prijave na studije.', rights: 'Sva prava zadržana.' },
  },
  hr: {
    localeName: 'Hrvatski',
    nav: { services: 'Usluge', process: 'Kako radimo', pricing: 'Cijene', faq: 'Pitanja', book: 'Rezervirajte razgovor' },
    hero: {
      eyebrow: 'Prijave na europska sveučilišta · savjetovanje na vašem jeziku', titleA: 'Studirajte vani.', titleB: 'Prijavite se s jasnim planom.',
      body: 'Zajedno pretvaramo izbor studija, troškove, stipendije i rokove u jasan plan za preddiplomsku ili diplomsku prijavu.',
      primary: 'Razjasnite sljedeći korak — 15 min besplatno', secondary: 'Pogledajte kako radimo',
    },
    trust: ['Neovisno savjetovanje', 'Osobna podrška', 'Jasne cijene'],
    route: {
      title: 'Vaša admissions ruta', live: 'jasno', next: 'Sljedeći korak', free: '15 min · bez naknade',
      stops: [['PROFIL', 'Polazna točka'], ['SMJER', 'Pravi programi'], ['PRIJAVA', 'Jasna priča']],
      note: 'Zajedno biramo smjer koji najbolje odgovara vašem cilju.',
    },
    signals: {
      kicker: 'Prije prve prijave', title: 'Prvo razjasnimo odluke koje grade dobru prijavu.',
      body: 'Profil, budžet, rokovi i ambicija postaju jedan ostvariv plan.',
      items: [
        ['Akademski fit', 'Prepoznajemo gdje ste najjači i kako to jasno pokazati.'],
        ['Budžet i stipendije', 'Od početka povezujemo troškove s dostupnim izvorima financiranja.'],
        ['Programi i zemlje', 'Svaki studij u užem izboru ima jasan razlog.'],
        ['Rokovi i ritam', 'Postavljamo prioritete, rokove i tjedni ritam.'],
      ],
    },
    services: {
      kicker: 'Usluge', title: 'Podrška onoliko široka koliko vam doista treba.',
      body: 'Počnite jednom strateškom sesijom ili radite s nama kroz cijeli prijavni ciklus.', cta: 'Razgovarajmo o vašem planu',
      cards: [
        { name: 'Strateško savjetovanje', price: '100 €', meta: '60 minuta', desc: 'Za konkretno pitanje, drugo mišljenje ili odluku koju trebate donijeti sada.', bullets: ['Razgovor 1 na 1', 'Jasni sljedeći koraci'] },
        { name: 'Admissions Blueprint', price: '240 €', meta: 'fiksna cijena', desc: 'Procjena profila i pisani plan koji postavlja smjer cijelog procesa.', bullets: ['Ulazna analiza profila', 'Strateški razgovor od 60 minuta', 'Pisani plan u roku od 5 radnih dana'] },
        { name: 'University Direction', price: 'od 490 €', meta: 'prema opsegu', desc: 'Obrazložen uži izbor studija, rokova, budžeta i ključnih zahtjeva.', bullets: ['Do 8 programa', 'Mapa rokova i troškova', 'Jedna revizija'] },
        { name: 'Full Application Partnership', price: '1.400–2.500 €', meta: 'prijavni ciklus', desc: 'Do četiri europska programa; dodatne, stipendijske i zahtjevnije UK/US prijave posebno se ugovaraju.', bullets: ['Plan i shortlist', 'Dvije revizije po dogovorenom dokumentu', 'Unaprijed definiran period podrške'], featured: true },
      ],
    },
    process: {
      kicker: 'Kako radimo', title: 'Jedan proces. Tri jasne faze.',
      steps: [
        ['Upoznajemo vas', 'Vaši interesi, iskustvo, budžet i rokovi.'],
        ['Gradimo realan plan', 'Prioriteti, uži izbor i konkretan ritam rada.'],
        ['Zajedno jačamo prijavu', 'Prava pitanja i iskren feedback pomažu da vaš glas dođe do izražaja.'],
      ],
    },
    principles: {
      kicker: 'Boutique po izboru', title: 'Vaš interes vodi svaku preporuku.',
      body: 'Svaki odabir provjeravamo prema akademskoj usklađenosti, trošku, rokovima, financiranju i realnim izgledima.',
      labels: [['01', 'Vaš interes na prvom mjestu'], ['02', 'Izravna podrška savjetnika'], ['03', 'Jasan opseg i cijena']],
      ethicsTitle: 'Vaš glas. Naša puna podrška.',
      ethicsBody: 'Maksimalno se trudimo da vaša prijava bude snažna, osobna i vjerodostojna. Vi zadržavate svoj glas; mi donosimo strukturu, prava pitanja i precizan feedback.',
    },
    pricing: {
      kicker: 'Transparentne cijene', title: 'Znate okvir prije prvog plaćanja.',
      body: 'Cjeloviti angažmani najčešće se kreću između 1.400 i 2.500 €, ovisno o broju programa, stipendija i složenosti procesa.',
      table: [
        ['Uvodni fit razgovor', '15 min', '0 €'], ['Strateško savjetovanje', '60 min', '100 €'],
        ['Admissions Blueprint', 'fiksno', '240 €'], ['University Direction', 'od', '490 €'],
        ['Prva standardna prijava', 'od', '250 €'], ['Savjetovanje za stipendije', 'od', '200 €'],
        ['Priprema za intervju', 'od', '150 €'], ['Privatno mentorstvo', 'po satu', '110 €'],
      ],
      note: 'Konačan opseg usluge i cijenu potvrđujemo pisanim putem prije plaćanja.',
    },
    faq: {
      kicker: 'Česta pitanja', title: 'Sve što trebate znati.',
      items: [
        ['Kako pomažete kandidatu izraditi što snažniju prijavu?', 'Svaku prijavu usmjeravamo prema kriterijima konkretnog programa. Zajedno gradimo strategiju, argumente, dokumente i pripremu za intervju, uz iskustvo s DAAD, Erasmus Mundus, OeAD i France Excellence stipendijama.'],
        ['Radite li bachelor i master prijave?', 'Da. Radimo s učenicima, studentima i obiteljima koje ciljaju međunarodne bachelor i master programe, prvenstveno u Europi.'],
        ['Kako radimo na motivacijskom pismu?', 'Vi zadržavate vlastiti glas, a mi pomažemo sa strukturom, argumentima, detaljnim feedbackom i revizijama.'],
        ['Mogu li uzeti samo jednu uslugu?', 'Da. Počnite savjetovanjem, strategijom ili shortlistom — onim što vam sada najviše koristi.'],
        ['Na kojem jeziku radimo?', 'Savjetovanje i sadržaj nudimo na bosanskom, hrvatskom, srpskom/crnogorskom, engleskom, njemačkom i francuskom.'],
        ['Što uključuje besplatan razgovor?', 'U 15 minuta upoznajemo vaš cilj, rokove i potrebe te dogovaramo najbolji sljedeći korak.'],
      ],
    },
    booking: {
      kicker: 'Sljedeći korak', title: '15 minuta za jasan sljedeći korak.',
      body: 'Odaberite termin, a mi ćemo upoznati vaš cilj, rokove i potrebe.',
      event: 'Besplatan uvodni razgovor', duration: '15 minuta', location: 'Online · video poziv', timezone: 'Automatska vremenska zona',
      button: 'Otvori booking kalendar', pending: 'Booking kalendar spreman za povezivanje',
      paid: 'Za potpunu strategiju odaberite savjetovanje od 60 minuta.',
    },
    footer: { line: 'Clarity for every step.', description: 'Osobna podrška za snažnije međunarodne prijave na studij.', rights: 'Sva prava pridržana.' },
  },
  en: {
    localeName: 'English',
    nav: { services: 'Services', process: 'How it works', pricing: 'Pricing', faq: 'FAQ', book: 'Book a call' },
    hero: {
      eyebrow: 'European university applications · guidance in your language', titleA: 'Study abroad.', titleB: 'Apply with a clear plan.',
      body: 'Together, we turn program choices, costs, funding and deadlines into a clear bachelor’s or master’s application plan.',
      primary: 'Clarify your next step — free 15 min', secondary: 'See how we work',
    },
    trust: ['Independent guidance', 'One-to-one support', 'Transparent pricing'],
    route: {
      title: 'Your admissions route', live: 'clear', next: 'Next step', free: '15 min · complimentary',
      stops: [['PROFILE', 'Starting point'], ['DIRECTION', 'Right programs'], ['APPLICATION', 'A clear story']],
      note: 'Together, we choose the direction that best fits your goal.',
    },
    signals: {
      kicker: 'Before the first application', title: 'First, we clarify the decisions that build a strong application.',
      body: 'Profile, budget, deadlines and ambition become one workable plan.',
      items: [
        ['Academic fit', 'We identify where you are strongest and how to show it clearly.'],
        ['Budget & funding', 'From the start, we connect costs with realistic funding options.'],
        ['Programs & countries', 'Every program on the shortlist has a clear reason.'],
        ['Deadlines & pace', 'We set priorities, deadlines and a weekly rhythm.'],
      ],
    },
    services: {
      kicker: 'Services', title: 'Support as focused—or as complete—as you need.',
      body: 'Start with one strategic session or work with us throughout the application cycle.', cta: 'Discuss your plan',
      cards: [
        { name: 'Strategy Consultation', price: '€100', meta: '60 minutes', desc: 'For a concrete question, a second opinion or a decision you need to make now.', bullets: ['One-to-one session', 'Clear next steps'] },
        { name: 'Admissions Blueprint', price: '€240', meta: 'fixed price', desc: 'A profile assessment and written plan that sets the direction for the process.', bullets: ['Profile intake', '60-minute strategy session', 'Written plan within 5 business days'] },
        { name: 'University Direction', price: 'from €490', meta: 'scope-based', desc: 'A reasoned shortlist with deadlines, costs and key requirements mapped out.', bullets: ['Up to 8 programs', 'Deadline & cost map', 'One revision'] },
        { name: 'Full Application Partnership', price: '€1,400–2,500', meta: 'application cycle', desc: 'Up to four European programs; extra, scholarship-heavy and complex UK/US applications are quoted separately.', bullets: ['Plan & shortlist', 'Two review rounds per agreed document', 'Defined support period'], featured: true },
      ],
    },
    process: {
      kicker: 'How it works', title: 'One process. Three clear phases.',
      steps: [
        ['Get to know you', 'Your interests, experience, budget and deadlines.'],
        ['Build a realistic plan', 'Priorities, a reasoned shortlist and a practical work rhythm.'],
        ['Strengthen the application together', 'The right questions and honest feedback help your voice stand out.'],
      ],
    },
    principles: {
      kicker: 'Boutique by design', title: 'Your interests guide every recommendation.',
      body: 'We test every choice against academic fit, total cost, deadlines, funding and realistic prospects.',
      labels: [['01', 'Your interests first'], ['02', 'Direct adviser support'], ['03', 'Clear scope & fees']],
      ethicsTitle: 'Your voice. Our full support.',
      ethicsBody: 'We put our full effort into making your application strong, personal and credible. You keep your voice; we bring structure, the right questions and precise feedback.',
    },
    pricing: {
      kicker: 'Transparent pricing', title: 'Know the range before you pay.',
      body: 'Complete engagements typically range from €1,400 to €2,500, depending on the number of programs, scholarship work and complexity.',
      table: [
        ['Introductory fit call', '15 min', '€0'], ['Expert consultation', '60 min', '€100'],
        ['Admissions Blueprint', 'fixed', '€240'], ['University Direction', 'from', '€490'],
        ['First standard application', 'from', '€250'], ['Scholarship advisory', 'from', '€200'],
        ['Interview preparation', 'from', '€150'], ['Private mentoring', 'per hour', '€110'],
      ],
      note: 'We confirm the final scope and fee in writing before payment.',
    },
    faq: {
      kicker: 'Frequently asked', title: 'Everything you need to know.',
      items: [
        ['How do you help applicants build the strongest possible application?', 'We align every application with the criteria of the specific programme. Together, we build the strategy, arguments, documents and interview preparation, drawing on experience with DAAD, Erasmus Mundus, OeAD and France Excellence scholarships.'],
        ['Do you support bachelor’s and master’s applicants?', 'Yes. We work with students and families targeting international bachelor’s and master’s programs, primarily across Europe.'],
        ['How do we work on motivation letters?', 'You keep your own voice; we help with structure, arguments, detailed feedback and revisions.'],
        ['Can I purchase just one service?', 'Yes. Start with the consultation, strategy or shortlist that helps you most right now.'],
        ['Which languages do you work in?', 'Guidance and content are available in Bosnian, Croatian, Serbian/Montenegrin, English, German and French.'],
        ['What happens in the free call?', 'In 15 minutes, we learn about your goals, timeline and needs and agree on the best next step.'],
      ],
    },
    booking: {
      kicker: 'Your next step', title: '15 minutes for a clear next step.',
      body: 'Choose a time, and we will learn about your goals, timeline and needs.',
      event: 'Free introductory call', duration: '15 minutes', location: 'Online · video call', timezone: 'Automatic time zone',
      button: 'Open booking calendar', pending: 'Booking calendar ready to connect',
      paid: 'For a complete strategy, choose a 60-minute consultation.',
    },
    footer: { line: 'Clarity for every step.', description: 'Personal support for stronger international university applications.', rights: 'All rights reserved.' },
  },
  de: {
    localeName: 'Deutsch',
    nav: { services: 'Leistungen', process: 'Ablauf', pricing: 'Preise', faq: 'FAQ', book: 'Gespräch buchen' },
    hero: {
      eyebrow: 'Bewerbungen an europäischen Hochschulen · Beratung in Ihrer Sprache', titleA: 'Im Ausland studieren.', titleB: 'Mit einem klaren Plan bewerben.',
      body: 'Gemeinsam machen wir aus Programmauswahl, Kosten, Förderung und Fristen einen klaren Plan für Ihre Bachelor- oder Masterbewerbung.',
      primary: 'Nächsten Schritt klären — 15 Min. kostenlos', secondary: 'So arbeiten wir',
    },
    trust: ['Unabhängige Beratung', 'Persönliche Begleitung', 'Transparente Preise'],
    route: {
      title: 'Ihr Bewerbungsweg', live: 'klar', next: 'Nächster Schritt', free: '15 Min. · kostenlos',
      stops: [['PROFIL', 'Ausgangslage'], ['RICHTUNG', 'Passende Programme'], ['BEWERBUNG', 'Eine klare Geschichte']],
      note: 'Gemeinsam wählen wir den Weg, der am besten zu Ihrem Ziel passt.',
    },
    signals: {
      kicker: 'Vor der ersten Bewerbung', title: 'Zuerst klären wir die Entscheidungen, die eine starke Bewerbung ausmachen.',
      body: 'Profil, Budget, Fristen und Ambition werden zu einem umsetzbaren Plan.',
      items: [
        ['Akademische Eignung', 'Wir erkennen Ihre Stärken und zeigen, wie sie klar sichtbar werden.'],
        ['Budget & Förderung', 'Von Anfang an verbinden wir Kosten mit realistischen Finanzierungsmöglichkeiten.'],
        ['Programme & Länder', 'Jedes Programm auf der engeren Auswahl hat einen klaren Grund.'],
        ['Fristen & Tempo', 'Wir setzen Prioritäten, Fristen und einen Wochenrhythmus.'],
      ],
    },
    services: {
      kicker: 'Leistungen', title: 'So fokussiert oder umfassend, wie Sie es benötigen.',
      body: 'Starten Sie mit einer Strategiesitzung oder arbeiten Sie mit uns durch den gesamten Bewerbungszyklus.', cta: 'Plan besprechen',
      cards: [
        { name: 'Strategieberatung', price: '100 €', meta: '60 Minuten', desc: 'Für eine konkrete Frage, eine zweite Einschätzung oder eine anstehende Entscheidung.', bullets: ['Persönliches Gespräch', 'Klare nächste Schritte'] },
        { name: 'Admissions Blueprint', price: '240 €', meta: 'Festpreis', desc: 'Profilanalyse und schriftlicher Plan als Richtung für den gesamten Prozess.', bullets: ['Profilaufnahme', '60-minütiges Strategiegespräch', 'Schriftlicher Plan in 5 Werktagen'] },
        { name: 'University Direction', price: 'ab 490 €', meta: 'nach Umfang', desc: 'Begründete Programmauswahl mit Fristen, Kosten und Anforderungen.', bullets: ['Bis zu 8 Programme', 'Fristen- und Kostenplan', 'Eine Überarbeitung'] },
        { name: 'Full Application Partnership', price: '1.400–2.500 €', meta: 'Bewerbungszyklus', desc: 'Bis zu vier europäische Programme; weitere, stipendienintensive und komplexe UK/US-Bewerbungen werden separat angeboten.', bullets: ['Plan & Shortlist', 'Zwei Feedbackrunden je vereinbartem Dokument', 'Definierter Betreuungszeitraum'], featured: true },
      ],
    },
    process: {
      kicker: 'So arbeiten wir', title: 'Ein Prozess. Drei klare Phasen.',
      steps: [
        ['Wir lernen Sie kennen', 'Ihre Interessen, Erfahrungen, Ihr Budget und Ihre Fristen.'],
        ['Wir entwickeln einen realistischen Plan', 'Prioritäten, eine begründete Auswahl und ein konkreter Arbeitsrhythmus.'],
        ['Wir stärken die Bewerbung gemeinsam', 'Die richtigen Fragen und ehrliches Feedback bringen Ihre Stimme zur Geltung.'],
      ],
    },
    principles: {
      kicker: 'Bewusst persönlich', title: 'Ihre Ziele leiten jede Empfehlung.',
      body: 'Jede Auswahl prüfen wir anhand akademischer Passung, Gesamtkosten, Fristen, Finanzierung und realistischer Chancen.',
      labels: [['01', 'Ihre Ziele zuerst'], ['02', 'Direkte Beratung'], ['03', 'Klarer Umfang & Preis']],
      ethicsTitle: 'Ihre Stimme. Unsere volle Unterstützung.',
      ethicsBody: 'Wir setzen uns mit vollem Einsatz dafür ein, dass Ihre Bewerbung stark, persönlich und glaubwürdig wird. Sie behalten Ihre Stimme; wir bringen Struktur, die richtigen Fragen und präzises Feedback.',
    },
    pricing: {
      kicker: 'Transparente Preise', title: 'Kennen Sie den Rahmen vor der Zahlung.',
      body: 'Komplette Begleitungen liegen meist zwischen 1.400 und 2.500 €, abhängig von Programmanzahl, Stipendienarbeit und Komplexität.',
      table: [
        ['Kennenlerngespräch', '15 Min.', '0 €'], ['Strategieberatung', '60 Min.', '100 €'],
        ['Admissions Blueprint', 'Festpreis', '240 €'], ['University Direction', 'ab', '490 €'],
        ['Erste Standardbewerbung', 'ab', '250 €'], ['Stipendienberatung', 'ab', '200 €'],
        ['Interviewvorbereitung', 'ab', '150 €'], ['Persönliches Mentoring', 'pro Std.', '110 €'],
      ],
      note: 'Den endgültigen Umfang und Preis bestätigen wir vor der Zahlung schriftlich.',
    },
    faq: {
      kicker: 'Häufige Fragen', title: 'Alles, was Sie wissen müssen.',
      items: [
        ['Wie helfen Sie Bewerber:innen, eine möglichst starke Bewerbung zu erstellen?', 'Wir richten jede Bewerbung konsequent an den Kriterien des jeweiligen Programms aus. Gemeinsam entwickeln wir Strategie, Argumentation, Unterlagen und Interviewvorbereitung – mit Erfahrung aus DAAD, Erasmus Mundus, OeAD und France Excellence.'],
        ['Begleiten Sie Bachelor- und Masterbewerbungen?', 'Ja. Wir arbeiten mit Schüler:innen, Studierenden und Familien für internationale Bachelor- und Masterprogramme, vor allem in Europa.'],
        ['Wie arbeiten wir am Motivationsschreiben?', 'Sie behalten Ihre eigene Stimme; wir helfen mit Struktur, Argumenten, detailliertem Feedback und Überarbeitungen.'],
        ['Kann ich nur eine einzelne Leistung buchen?', 'Ja. Beginnen Sie mit der Beratung, Strategie oder Auswahl, die Ihnen jetzt am meisten hilft.'],
        ['In welchen Sprachen beraten Sie?', 'Beratung und Inhalte sind auf Bosnisch, Kroatisch, Serbisch/Montenegrinisch, Englisch, Deutsch und Französisch verfügbar.'],
        ['Was beinhaltet das kostenlose Gespräch?', 'In 15 Minuten lernen wir Ihre Ziele, Fristen und Ihren Bedarf kennen und vereinbaren den besten nächsten Schritt.'],
      ],
    },
    booking: {
      kicker: 'Nächster Schritt', title: '15 Minuten für einen klaren nächsten Schritt.',
      body: 'Wählen Sie einen Termin; wir lernen Ihre Ziele, Fristen und Ihren Bedarf kennen.',
      event: 'Kostenloses Kennenlerngespräch', duration: '15 Minuten', location: 'Online · Videoanruf', timezone: 'Automatische Zeitzone',
      button: 'Buchungskalender öffnen', pending: 'Buchungskalender bereit zur Verbindung',
      paid: 'Für eine vollständige Strategie wählen Sie die 60-minütige Strategieberatung.',
    },
    footer: { line: 'Klarheit bei jedem Schritt.', description: 'Persönliche Unterstützung für stärkere internationale Hochschulbewerbungen.', rights: 'Alle Rechte vorbehalten.' },
  },
  fr: {
    localeName: 'Français',
    nav: { services: 'Services', process: 'Notre méthode', pricing: 'Tarifs', faq: 'Questions', book: 'Réserver un appel' },
    hero: {
      eyebrow: 'Candidatures universitaires en Europe · conseil dans votre langue', titleA: 'Étudiez à l’étranger.', titleB: 'Candidatez avec une stratégie claire.',
      body: 'Ensemble, nous transformons le choix des programmes, les coûts, les financements et les échéances en un plan clair pour votre candidature en licence ou en master.',
      primary: 'Clarifiez la prochaine étape — 15 min offertes', secondary: 'Voir notre méthode',
    },
    trust: ['Conseil indépendant', 'Accompagnement individuel', 'Tarifs transparents'],
    route: {
      title: 'Votre parcours d’admission', live: 'clair', next: 'Prochaine étape', free: '15 min · offert',
      stops: [['PROFIL', 'Point de départ'], ['DIRECTION', 'Bons programmes'], ['CANDIDATURE', 'Une histoire claire']],
      note: 'Ensemble, nous choisissons la voie la plus adaptée à votre objectif.',
    },
    signals: {
      kicker: 'Avant la première candidature', title: 'Nous clarifions d’abord les décisions qui construisent une candidature solide.',
      body: 'Profil, budget, échéances et ambition deviennent un plan réalisable.',
      items: [
        ['Adéquation académique', 'Nous identifions vos points forts et la meilleure façon de les mettre en valeur.'],
        ['Budget et financement', 'Dès le départ, nous relions les coûts aux possibilités réalistes de financement.'],
        ['Programmes et pays', 'Chaque programme retenu répond à une raison claire.'],
        ['Échéances et rythme', 'Nous fixons les priorités, les échéances et un rythme hebdomadaire.'],
      ],
    },
    services: {
      kicker: 'Services', title: 'Un accompagnement aussi ciblé — ou complet — que nécessaire.',
      body: 'Commencez par une séance stratégique ou travaillez avec nous pendant tout le cycle de candidature.', cta: 'Parler de votre projet',
      cards: [
        { name: 'Consultation stratégique', price: '100 €', meta: '60 minutes', desc: 'Pour une question précise, un second avis ou une décision à prendre maintenant.', bullets: ['Séance individuelle', 'Prochaines étapes claires'] },
        { name: 'Admissions Blueprint', price: '240 €', meta: 'prix fixe', desc: 'Une évaluation du profil et un plan écrit qui donnent une direction au processus.', bullets: ['Collecte des informations du profil', 'Séance stratégique de 60 minutes', 'Plan écrit sous 5 jours ouvrés'] },
        { name: 'University Direction', price: 'dès 490 €', meta: 'selon le périmètre', desc: 'Une sélection argumentée avec échéances, coûts et exigences clés.', bullets: ['Jusqu’à 8 programmes', 'Carte des délais et coûts', 'Une révision'] },
        { name: 'Full Application Partnership', price: '1 400–2 500 €', meta: 'cycle de candidature', desc: 'Jusqu’à quatre programmes européens ; les candidatures supplémentaires, avec bourses ou complexes au Royaume-Uni/aux États-Unis font l’objet d’un devis séparé.', bullets: ['Plan et sélection', 'Deux révisions par document convenu', 'Période d’accompagnement définie'], featured: true },
      ],
    },
    process: {
      kicker: 'Notre méthode', title: 'Un processus. Trois étapes claires.',
      steps: [
        ['Nous apprenons à vous connaître', 'Vos intérêts, votre expérience, votre budget et vos échéances.'],
        ['Nous construisons un plan réaliste', 'Des priorités, une sélection argumentée et un rythme de travail concret.'],
        ['Nous renforçons la candidature ensemble', 'Les bonnes questions et un retour honnête mettent votre voix en valeur.'],
      ],
    },
    principles: {
      kicker: 'Un choix délibérément boutique', title: 'Vos intérêts guident chaque recommandation.',
      body: 'Chaque choix est évalué selon l’adéquation académique, le coût total, les échéances, les financements et les perspectives réalistes.',
      labels: [['01', 'Vos intérêts d’abord'], ['02', 'Conseil direct'], ['03', 'Périmètre et tarifs clairs']],
      ethicsTitle: 'Votre voix. Notre plein engagement.',
      ethicsBody: 'Nous mettons toute notre énergie au service d’une candidature solide, personnelle et crédible. Vous gardez votre voix ; nous apportons la structure, les bonnes questions et un retour précis.',
    },
    pricing: {
      kicker: 'Tarifs transparents', title: 'Connaissez la fourchette avant de payer.',
      body: 'Un accompagnement complet se situe généralement entre 1 400 € et 2 500 €, selon le nombre de programmes, le travail sur les bourses et la complexité.',
      table: [
        ['Appel de découverte', '15 min', '0 €'], ['Consultation stratégique', '60 min', '100 €'],
        ['Admissions Blueprint', 'forfait', '240 €'], ['University Direction', 'dès', '490 €'],
        ['Première candidature standard', 'dès', '250 €'], ['Conseil en bourses', 'dès', '200 €'],
        ['Préparation à l’entretien', 'dès', '150 €'], ['Mentorat individuel', 'par heure', '110 €'],
      ],
      note: 'Nous confirmons par écrit le périmètre final et le tarif avant tout paiement.',
    },
    faq: {
      kicker: 'Questions fréquentes', title: 'Tout ce qu’il faut savoir.',
      items: [
        ['Comment aidez-vous les candidats à construire le meilleur dossier possible ?', 'Nous alignons chaque dossier sur les critères du programme visé. Ensemble, nous travaillons la stratégie, les arguments, les documents et les entretiens, avec une expérience des bourses DAAD, Erasmus Mundus, OeAD et France Excellence.'],
        ['Accompagnez-vous les candidatures en licence et en master ?', 'Oui. Nous travaillons avec des élèves, étudiants et familles visant des programmes internationaux de licence et de master, principalement en Europe.'],
        ['Comment travaillons-nous la lettre de motivation ?', 'Vous gardez votre voix ; nous vous aidons à structurer les arguments, puis apportons un retour détaillé et des révisions.'],
        ['Puis-je choisir un seul service ?', 'Oui. Commencez par la consultation, la stratégie ou la sélection qui vous aide le plus maintenant.'],
        ['Dans quelles langues travaillez-vous ?', 'Le conseil et les contenus sont disponibles en bosnien, croate, serbe/monténégrin, anglais, allemand et français.'],
        ['Que comprend l’appel gratuit ?', 'En 15 minutes, nous découvrons vos objectifs, vos échéances et vos besoins, puis convenons de la meilleure prochaine étape.'],
      ],
    },
    booking: {
      kicker: 'Prochaine étape', title: '15 minutes pour une prochaine étape claire.',
      body: 'Choisissez un créneau ; nous découvrons votre objectif, vos échéances et vos besoins.',
      event: 'Appel découverte gratuit', duration: '15 minutes', location: 'En ligne · visioconférence', timezone: 'Fuseau horaire automatique',
      button: 'Ouvrir le calendrier', pending: 'Calendrier de réservation prêt à être connecté',
      paid: 'Pour une stratégie complète, choisissez la consultation de 60 minutes.',
    },
    footer: { line: 'De la clarté à chaque étape.', description: 'Un accompagnement personnel pour des candidatures internationales plus solides.', rights: 'Tous droits réservés.' },
  },
} as const;

export type Locale = keyof typeof translations;
