export const translations = {
  bs: {
    localeName: 'Bosanski',
    nav: { services: 'Usluge', process: 'Kako radimo', pricing: 'Cijene', faq: 'Pitanja', book: 'Zakažite razgovor' },
    hero: {
      eyebrow: 'Prijave na evropske univerzitete · savjetovanje na vašem jeziku',
      titleA: 'Studirajte u inostranstvu.',
      titleB: 'Prijavite se s jasnim planom.',
      body: 'Nezavisno savjetovanje za evropske bachelor i master prijave — programi, troškovi, stipendije i rokovi povezani u jedan realan plan.',
      primary: 'Razjasnite sljedeći korak — 15 min besplatno',
      secondary: 'Pogledajte kako radimo',
    },
    trust: ['Nezavisno savjetovanje', 'Rad 1 na 1', 'Jasne cijene'],
    route: {
      title: 'Vaša admissions ruta', live: 'jasno', next: 'Sljedeći korak', free: '15 min · bez naknade',
      stops: [['PROFIL', 'Polazna tačka'], ['SMJER', 'Pravi programi'], ['PRIJAVA', 'Jasna priča']],
      note: 'Ne biramo univerzitet umjesto vas. Pomažemo da donesete bolju odluku.',
    },
    signals: {
      kicker: 'Prije prve prijave',
      title: 'Prvo mapiramo odluke koje zapravo određuju ishod.',
      body: 'Dobra strategija povezuje akademski profil, finansije, rokove i ambiciju. Tek onda biramo programe i oblikujemo prijavu.',
      items: [
        ['Akademski fit', 'Procjenjujemo gdje je vaš profil konkurentan i gdje treba ojačati priču.'],
        ['Budžet i stipendije', 'Troškove i realne izvore finansiranja uključujemo od prvog dana.'],
        ['Programi i zemlje', 'Ne pravimo generičku listu; svaki izbor mora imati jasan razlog.'],
        ['Rokovi i ritam', 'Kompleksan proces pretvaramo u prioritete, rokove i sedmični plan.'],
      ],
    },
    services: {
      kicker: 'Usluge',
      title: 'Podrška onoliko široka koliko vam zaista treba.',
      body: 'Počnite jednom strateškom sesijom ili radite s nama kroz cijeli prijavni ciklus.',
      cta: 'Razgovarajmo o vašem planu',
      cards: [
        { name: 'Strateška konsultacija', price: '100 €', meta: '60 minuta', desc: 'Za konkretno pitanje, drugu procjenu ili odluku koju trebate donijeti sada.', bullets: ['Razgovor 1 na 1', 'Jasni naredni koraci'] },
        { name: 'Admissions Blueprint', price: '240 €', meta: 'fiksna cijena', desc: 'Procjena profila i pisani plan koji postavlja smjer cijelog procesa.', bullets: ['Ulazna analiza profila', 'Strateški razgovor od 60 minuta', 'Pisani plan u roku od 5 radnih dana'] },
        { name: 'University Direction', price: 'od 490 €', meta: 'prema obimu', desc: 'Obrazložen uži izbor programa, rokova, budžeta i ključnih zahtjeva.', bullets: ['Do 8 programa', 'Mapa rokova i troškova', 'Jedna revizija'] },
        { name: 'Full Application Partnership', price: '1.400–2.500 €', meta: 'prijavni ciklus', desc: 'Do četiri evropska programa; dodatne, stipendijske i zahtjevnije UK/US prijave posebno se ugovaraju.', bullets: ['Plan i shortlist', 'Dvije revizije po dogovorenom dokumentu', 'Unaprijed definisan period podrške'], featured: true },
      ],
    },
    process: {
      kicker: 'Kako radimo',
      title: 'Jedan proces. Tri jasne faze.',
      steps: [
        ['Upoznajemo vašu polaznu tačku', 'Profil, interesi, budžet, rokovi i ograničenja — bez uljepšavanja i bez generičnih savjeta.'],
        ['Mapiramo realan put', 'Prioriteti, uži izbor i konkretan plan rada zasnovan na vašem cilju.'],
        ['Vodimo prijavu sa strukturom', 'Dajemo pitanja i iskren feedback; ideje, glas i konačne odluke ostaju vaši.'],
      ],
    },
    principles: {
      kicker: 'Boutique po izboru',
      title: 'Nismo prodajni kanal univerziteta.',
      body: 'Preporuke zasnivamo na vašem profilu, ciljevima, budžetu i rokovima. Ne obećavamo prijem; gradimo proces u kojem svaka odluka ima razlog.',
      labels: [['01', 'Nezavisna procjena'], ['02', 'Direktan rad sa savjetnikom'], ['03', 'Transparentan obim i cijena']],
      ethicsTitle: 'Vaša prijava ostaje vaša.',
      ethicsBody: 'Ne pišemo eseje umjesto kandidata i ne obećavamo prijem ili stipendiju. Dajemo strukturu, prava pitanja i povratne informacije kako biste svoju priču predstavili jasno i vjerodostojno.',
    },
    pricing: {
      kicker: 'Transparentne cijene',
      title: 'Znate okvir prije prvog plaćanja.',
      body: 'Kompletni angažmani se najčešće kreću između 1.400 i 2.500 €, zavisno od broja programa, stipendija i složenosti procesa.',
      table: [
        ['Uvodni fit razgovor', '15 min', '0 €'],
        ['Ekspertska konsultacija', '60 min', '100 €'],
        ['Admissions Blueprint', 'fiksno', '240 €'],
        ['University Direction', 'od', '490 €'],
        ['Prva standardna prijava', 'od', '250 €'],
        ['Scholarship advisory', 'od', '200 €'],
        ['Priprema za intervju', 'od', '150 €'],
        ['Privatno mentorstvo', 'po satu', '110 €'],
      ],
      note: 'Konačan obim usluge i cijenu potvrđujemo pisanim putem prije plaćanja.',
    },
    faq: {
      kicker: 'Česta pitanja',
      title: 'Prije nego rezervišete.',
      items: [
        ['Kako pomažete kandidatu da napravi što snažniju prijavu?', 'Radimo individualno i maksimalno usmjeravamo kandidata prema kriterijima konkretnog programa — od strategije i izbora programa do argumenata, dokumenata i intervjua. Generički tekstovi, uključujući one nastale automatizovanim alatima bez ličnog konteksta, često ne pokazuju motivaciju, iskustvo i stvarnu usklađenost kandidata s programom. Naši stručnjaci imaju iskustvo s DAAD, Erasmus Mundus, OeAD i France Excellence stipendijskim programima.'],
        ['Da li radite bachelor i master prijave?', 'Da. Radimo s učenicima, studentima i porodicama koje ciljaju međunarodne bachelor i master programe, prvenstveno u Evropi.'],
        ['Pišete li motivaciona pisma umjesto kandidata?', 'Ne. Pomažemo da razvijete strukturu, argumente i vlastiti glas, a zatim dajemo detaljan feedback i revizije.'],
        ['Mogu li uzeti samo jednu uslugu?', 'Da. Možete početi konsultacijom, strategijom ili shortlistom bez obaveze da uzmete puni paket.'],
        ['Na kojem jeziku radimo?', 'Savjetovanje i sadržaj nudimo na bosanskom, hrvatskom, srpskom/crnogorskom, engleskom, njemačkom i francuskom.'],
        ['Šta uključuje besplatan razgovor?', 'Upoznajemo cilj, rokove i potrebe te provjeravamo da li smo dobar izbor. Ne uključuje detaljnu procjenu profila ili listu univerziteta.'],
      ],
    },
    booking: {
      kicker: 'Sljedeći korak',
      title: '15 minuta da vidimo postoji li dobar fit.',
      body: 'Kalendar vas povezuje s jednim dostupnim članom tima i automatski prepoznaje vremensku zonu. Razgovor pokriva cilj, rokove i uzajamni fit.',
      event: 'Besplatan uvodni razgovor', duration: '15 minuta', location: 'Online · video poziv', timezone: 'Automatska vremenska zona',
      button: 'Otvori booking kalendar', pending: 'Booking kalendar spreman za povezivanje',
      paid: 'Za detaljnu procjenu profila rezervišite stratešku konsultaciju od 60 minuta.',
    },
    footer: {
      line: 'Clarity for every step.',
      description: 'Nezavisno savjetovanje za međunarodne prijave na studije.',
      rights: 'Sva prava zadržana.',
    },
  },
  sr: {
    localeName: 'Srpski',
    nav: { services: 'Usluge', process: 'Kako radimo', pricing: 'Cene', faq: 'Pitanja', book: 'Zakažite razgovor' },
    hero: {
      eyebrow: 'Prijave na evropske univerzitete · savetovanje na vašem jeziku',
      titleA: 'Studirajte u inostranstvu.',
      titleB: 'Prijavite se sa jasnim planom.',
      body: 'Nezavisno savetovanje za prijave na evropske osnovne i master studije — programi, troškovi, stipendije i rokovi povezani u jedan realan plan.',
      primary: 'Razjasnite sledeći korak — 15 min besplatno',
      secondary: 'Pogledajte kako radimo',
    },
    trust: ['Nezavisno savetovanje', 'Rad 1 na 1', 'Jasne cene'],
    route: {
      title: 'Vaša admissions ruta', live: 'jasno', next: 'Sledeći korak', free: '15 min · bez naknade',
      stops: [['PROFIL', 'Polazna tačka'], ['SMER', 'Pravi programi'], ['PRIJAVA', 'Jasna priča']],
      note: 'Ne biramo univerzitet umesto vas. Pomažemo da donesete bolju odluku.',
    },
    signals: {
      kicker: 'Pre prve prijave', title: 'Prvo mapiramo odluke koje zaista određuju ishod.',
      body: 'Dobra strategija povezuje akademski profil, finansije, rokove i ambiciju. Tek onda biramo programe i oblikujemo prijavu.',
      items: [
        ['Akademski fit', 'Procenjujemo gde je vaš profil konkurentan i gde treba ojačati priču.'],
        ['Budžet i stipendije', 'Troškove i realne izvore finansiranja uključujemo od prvog dana.'],
        ['Programi i zemlje', 'Ne pravimo generičku listu; svaki izbor mora imati jasan razlog.'],
        ['Rokovi i ritam', 'Kompleksan proces pretvaramo u prioritete, rokove i nedeljni plan.'],
      ],
    },
    services: {
      kicker: 'Usluge', title: 'Podrška onoliko široka koliko vam zaista treba.',
      body: 'Počnite jednom strateškom sesijom ili radite s nama kroz ceo prijavni ciklus.', cta: 'Razgovarajmo o vašem planu',
      cards: [
        { name: 'Strateška konsultacija', price: '100 €', meta: '60 minuta', desc: 'Za konkretno pitanje, drugo mišljenje ili odluku koju treba da donesete sada.', bullets: ['Razgovor 1 na 1', 'Jasni naredni koraci'] },
        { name: 'Admissions Blueprint', price: '240 €', meta: 'fiksna cena', desc: 'Procena profila i pisani plan koji postavlja smer celog procesa.', bullets: ['Ulazna analiza profila', 'Strateški razgovor od 60 minuta', 'Pisani plan u roku od 5 radnih dana'] },
        { name: 'University Direction', price: 'od 490 €', meta: 'prema obimu', desc: 'Obrazložen uži izbor programa, rokova, budžeta i ključnih zahteva.', bullets: ['Do 8 programa', 'Mapa rokova i troškova', 'Jedna revizija'] },
        { name: 'Full Application Partnership', price: '1.400–2.500 €', meta: 'prijavni ciklus', desc: 'Do četiri evropska programa; dodatne, stipendijske i zahtevnije UK/US prijave posebno se ugovaraju.', bullets: ['Plan i shortlist', 'Dve revizije po dogovorenom dokumentu', 'Unapred definisan period podrške'], featured: true },
      ],
    },
    process: {
      kicker: 'Kako radimo', title: 'Jedan proces. Tri jasne faze.',
      steps: [
        ['Upoznajemo vašu polaznu tačku', 'Profil, interesovanja, budžet, rokovi i ograničenja — bez ulepšavanja i generičnih saveta.'],
        ['Mapiramo realan put', 'Prioriteti, uži izbor i konkretan plan rada zasnovan na vašem cilju.'],
        ['Vodimo prijavu sa strukturom', 'Dajemo pitanja i iskren feedback; ideje, glas i konačne odluke ostaju vaši.'],
      ],
    },
    principles: {
      kicker: 'Boutique po izboru', title: 'Nismo prodajni kanal univerziteta.',
      body: 'Preporuke zasnivamo na vašem profilu, ciljevima, budžetu i rokovima. Ne obećavamo prijem; gradimo proces u kojem svaka odluka ima razlog.',
      labels: [['01', 'Nezavisna procena'], ['02', 'Direktan rad sa savetnikom'], ['03', 'Transparentan obim i cena']],
      ethicsTitle: 'Vaša prijava ostaje vaša.',
      ethicsBody: 'Ne pišemo eseje umesto kandidata i ne obećavamo prijem ili stipendiju. Dajemo strukturu, prava pitanja i povratne informacije kako biste svoju priču predstavili jasno i autentično.',
    },
    pricing: {
      kicker: 'Transparentne cene', title: 'Znate okvir pre prvog plaćanja.',
      body: 'Kompletni angažmani se najčešće kreću između 1.400 i 2.500 €, zavisno od broja programa, stipendija i složenosti procesa.',
      table: [
        ['Uvodni fit razgovor', '15 min', '0 €'], ['Ekspertska konsultacija', '60 min', '100 €'],
        ['Admissions Blueprint', 'fiksno', '240 €'], ['University Direction', 'od', '490 €'],
        ['Prva standardna prijava', 'od', '250 €'], ['Scholarship advisory', 'od', '200 €'],
        ['Priprema za intervju', 'od', '150 €'], ['Privatno mentorstvo', 'po satu', '110 €'],
      ],
      note: 'Konačan obim usluge i cenu potvrđujemo pisanim putem pre plaćanja.',
    },
    faq: {
      kicker: 'Česta pitanja', title: 'Pre nego što rezervišete.',
      items: [
        ['Kako pomažete kandidatu da napravi što snažniju prijavu?', 'Radimo individualno i maksimalno usmeravamo kandidata prema kriterijumima konkretnog programa — od strategije i izbora programa do argumenata, dokumenata i intervjua. Generički tekstovi, uključujući one nastale automatizovanim alatima bez ličnog konteksta, često ne pokazuju motivaciju, iskustvo i stvarnu usklađenost kandidata sa programom. Naši stručnjaci imaju iskustvo sa DAAD, Erasmus Mundus, OeAD i France Excellence stipendijskim programima.'],
        ['Da li radite bachelor i master prijave?', 'Da. Radimo sa učenicima, studentima i porodicama koje ciljaju međunarodne bachelor i master programe, prvenstveno u Evropi.'],
        ['Pišete li motivaciona pisma umesto kandidata?', 'Ne. Pomažemo da razvijete strukturu, argumente i svoj glas, a zatim dajemo detaljan feedback i revizije.'],
        ['Mogu li uzeti samo jednu uslugu?', 'Da. Možete početi konsultacijom, strategijom ili shortlistom bez obaveze da uzmete puni paket.'],
        ['Na kom jeziku radimo?', 'Savetovanje i sadržaj nudimo na bosanskom, hrvatskom, srpskom/crnogorskom, engleskom, nemačkom i francuskom.'],
        ['Šta uključuje besplatan razgovor?', 'Upoznajemo cilj, rokove i potrebe i proveravamo da li smo dobar izbor. Ne uključuje detaljnu procenu profila ili listu univerziteta.'],
      ],
    },
    booking: {
      kicker: 'Sledeći korak', title: '15 minuta da vidimo postoji li dobar fit.',
      body: 'Kalendar vas povezuje sa jednim dostupnim članom tima i automatski prepoznaje vremensku zonu. Razgovor pokriva cilj, rokove i uzajamni fit.',
      event: 'Besplatan uvodni razgovor', duration: '15 minuta', location: 'Online · video poziv', timezone: 'Automatska vremenska zona',
      button: 'Otvori booking kalendar', pending: 'Booking kalendar spreman za povezivanje',
      paid: 'Za detaljnu procenu profila rezervišite stratešku konsultaciju od 60 minuta.',
    },
    footer: { line: 'Clarity for every step.', description: 'Nezavisno savetovanje za međunarodne prijave na studije.', rights: 'Sva prava zadržana.' },
  },
  hr: {
    localeName: 'Hrvatski',
    nav: { services: 'Usluge', process: 'Kako radimo', pricing: 'Cijene', faq: 'Pitanja', book: 'Rezervirajte razgovor' },
    hero: {
      eyebrow: 'Prijave na europska sveučilišta · savjetovanje na vašem jeziku', titleA: 'Studirajte vani.', titleB: 'Prijavite se s jasnim planom.',
      body: 'Neovisno savjetovanje za prijave na europske preddiplomske i diplomske studije — programi, troškovi, stipendije i rokovi povezani u jedan realan plan.',
      primary: 'Razjasnite sljedeći korak — 15 min besplatno', secondary: 'Pogledajte kako radimo',
    },
    trust: ['Neovisno savjetovanje', 'Osobna podrška', 'Jasne cijene'],
    route: {
      title: 'Vaša admissions ruta', live: 'jasno', next: 'Sljedeći korak', free: '15 min · bez naknade',
      stops: [['PROFIL', 'Polazna točka'], ['SMJER', 'Pravi programi'], ['PRIJAVA', 'Jasna priča']],
      note: 'Ne biramo studij umjesto vas. Pomažemo vam donijeti bolju odluku.',
    },
    signals: {
      kicker: 'Prije prve prijave', title: 'Prvo mapiramo odluke koje doista određuju ishod.',
      body: 'Dobra strategija povezuje akademski profil, financije, rokove i ambiciju. Tek onda biramo programe i oblikujemo prijavu.',
      items: [
        ['Akademski fit', 'Procjenjujemo gdje je vaš profil konkurentan i gdje treba ojačati priču.'],
        ['Budžet i stipendije', 'Troškove i realne izvore financiranja uključujemo od prvog dana.'],
        ['Programi i zemlje', 'Ne radimo generičku listu; svaki odabir mora imati jasan razlog.'],
        ['Rokovi i ritam', 'Složen proces pretvaramo u prioritete, rokove i tjedni plan.'],
      ],
    },
    services: {
      kicker: 'Usluge', title: 'Podrška onoliko široka koliko vam doista treba.',
      body: 'Počnite jednom strateškom sesijom ili radite s nama kroz cijeli prijavni ciklus.', cta: 'Razgovarajmo o vašem planu',
      cards: [
        { name: 'Strateško savjetovanje', price: '100 €', meta: '60 minuta', desc: 'Za konkretno pitanje, drugo mišljenje ili odluku koju trebate donijeti sada.', bullets: ['Razgovor 1 na 1', 'Jasni sljedeći koraci'] },
        { name: 'Admissions Blueprint', price: '240 €', meta: 'fiksna cijena', desc: 'Procjena profila i pisani plan koji postavlja smjer cijelog procesa.', bullets: ['Ulazna analiza profila', 'Strateški razgovor od 60 minuta', 'Pisani plan u roku od 5 radnih dana'] },
        { name: 'University Direction', price: 'od 490 €', meta: 'prema opsegu', desc: 'Obrazložen uži izbor studija, rokova, budžeta i ključnih zahtjeva.', bullets: ['Do 8 programa', 'Mapa rokova i troškova', 'Jedna revizija'] },
        { name: 'Full Application Partnership', price: '1.400–2.500 €', meta: 'prijavni ciklus', desc: 'Do četiri europska programa; dodatne, stipendijske i zahtjevnije UK/US prijave posebno se ugovaraju.', bullets: ['Plan i shortlist', 'Dvije revizije po dogovorenom dokumentu', 'Unaprijed definiran period podrške'], featured: true },
      ],
    },
    process: {
      kicker: 'Kako radimo', title: 'Jedan proces. Tri jasne faze.',
      steps: [
        ['Upoznajemo vašu polaznu točku', 'Profil, interesi, budžet, rokovi i ograničenja — bez uljepšavanja i generičkih savjeta.'],
        ['Mapiramo realan put', 'Prioriteti, uži izbor i konkretan plan rada zasnovan na vašem cilju.'],
        ['Vodimo prijavu sa strukturom', 'Dajemo pitanja i iskren feedback; ideje, glas i konačne odluke ostaju vaši.'],
      ],
    },
    principles: {
      kicker: 'Boutique po izboru', title: 'Nismo prodajni kanal sveučilišta.',
      body: 'Preporuke zasnivamo na vašem profilu, ciljevima, budžetu i rokovima. Ne obećavamo upis; gradimo proces u kojem svaka odluka ima razlog.',
      labels: [['01', 'Neovisna procjena'], ['02', 'Izravan rad sa savjetnikom'], ['03', 'Transparentan opseg i cijena']],
      ethicsTitle: 'Vaša prijava ostaje vaša.',
      ethicsBody: 'Ne pišemo eseje umjesto kandidata i ne obećavamo upis ili stipendiju. Dajemo strukturu, prava pitanja i povratne informacije kako biste svoju priču predstavili jasno i autentično.',
    },
    pricing: {
      kicker: 'Transparentne cijene', title: 'Znate okvir prije prvog plaćanja.',
      body: 'Cjeloviti angažmani najčešće se kreću između 1.400 i 2.500 €, ovisno o broju programa, stipendija i složenosti procesa.',
      table: [
        ['Uvodni fit razgovor', '15 min', '0 €'], ['Strateško savjetovanje', '60 min', '100 €'],
        ['Admissions Blueprint', 'fiksno', '240 €'], ['University Direction', 'od', '490 €'],
        ['Prva standardna prijava', 'od', '250 €'], ['Savjetovanje za stipendije', 'od', '200 €'],
        ['Priprema za intervju', 'od', '150 €'], ['Privatno mentorstvo', 'po satu', '110 €'],
      ],
      note: 'Konačan opseg usluge i cijenu potvrđujemo pisanim putem prije plaćanja.',
    },
    faq: {
      kicker: 'Česta pitanja', title: 'Prije nego rezervirate.',
      items: [
        ['Kako pomažete kandidatu izraditi što snažniju prijavu?', 'Radimo individualno i maksimalno usmjeravamo kandidata prema kriterijima konkretnog programa — od strategije i izbora programa do argumenata, dokumenata i intervjua. Generički tekstovi, uključujući one nastale automatiziranim alatima bez osobnog konteksta, često ne pokazuju motivaciju, iskustvo i stvarnu usklađenost kandidata s programom. Naši stručnjaci imaju iskustvo s DAAD, Erasmus Mundus, OeAD i France Excellence stipendijskim programima.'],
        ['Radite li bachelor i master prijave?', 'Da. Radimo s učenicima, studentima i obiteljima koje ciljaju međunarodne bachelor i master programe, prvenstveno u Europi.'],
        ['Pišete li motivacijska pisma umjesto kandidata?', 'Ne. Pomažemo vam razviti strukturu, argumente i vlastiti glas, a zatim dajemo detaljan feedback i revizije.'],
        ['Mogu li uzeti samo jednu uslugu?', 'Da. Možete početi savjetovanjem, strategijom ili shortlistom bez obveze da uzmete puni paket.'],
        ['Na kojem jeziku radimo?', 'Savjetovanje i sadržaj nudimo na bosanskom, hrvatskom, srpskom/crnogorskom, engleskom, njemačkom i francuskom.'],
        ['Što uključuje besplatan razgovor?', 'Upoznajemo cilj, rokove i potrebe te provjeravamo odgovaramo li vam. Ne uključuje detaljnu procjenu profila ili listu sveučilišta.'],
      ],
    },
    booking: {
      kicker: 'Sljedeći korak', title: '15 minuta da vidimo postoji li dobar fit.',
      body: 'Kalendar vas povezuje s jednim dostupnim članom tima i automatski prepoznaje vremensku zonu. Razgovor pokriva cilj, rokove i međusobni fit.',
      event: 'Besplatan uvodni razgovor', duration: '15 minuta', location: 'Online · video poziv', timezone: 'Automatska vremenska zona',
      button: 'Otvori booking kalendar', pending: 'Booking kalendar spreman za povezivanje',
      paid: 'Za detaljnu procjenu profila rezervirajte strateško savjetovanje od 60 minuta.',
    },
    footer: { line: 'Clarity for every step.', description: 'Neovisno savjetovanje za međunarodne prijave na studij.', rights: 'Sva prava pridržana.' },
  },
  en: {
    localeName: 'English',
    nav: { services: 'Services', process: 'How it works', pricing: 'Pricing', faq: 'FAQ', book: 'Book a call' },
    hero: {
      eyebrow: 'European university applications · guidance in your language', titleA: 'Study abroad.', titleB: 'Apply with a clear plan.',
      body: 'Independent guidance for European bachelor’s and master’s applications—programs, costs, funding and deadlines aligned in one realistic plan.',
      primary: 'Clarify your next step — free 15 min', secondary: 'See how we work',
    },
    trust: ['Independent guidance', 'One-to-one support', 'Transparent pricing'],
    route: {
      title: 'Your admissions route', live: 'clear', next: 'Next step', free: '15 min · complimentary',
      stops: [['PROFILE', 'Starting point'], ['DIRECTION', 'Right programs'], ['APPLICATION', 'A clear story']],
      note: 'We do not choose a university for you. We help you make a better decision.',
    },
    signals: {
      kicker: 'Before the first application', title: 'First, we map the decisions that actually shape the outcome.',
      body: 'A sound strategy connects academic fit, finances, deadlines and ambition. Only then do we choose programs and shape the application.',
      items: [
        ['Academic fit', 'We assess where your profile is competitive and where your story needs work.'],
        ['Budget & funding', 'Costs and realistic sources of funding enter the plan from day one.'],
        ['Programs & countries', 'No generic lists; every recommendation needs a clear reason.'],
        ['Deadlines & pace', 'We turn a complex process into priorities, deadlines and a weekly rhythm.'],
      ],
    },
    services: {
      kicker: 'Services', title: 'Support as focused—or as complete—as you need.',
      body: 'Start with one strategic session or work with us throughout the application cycle.', cta: 'Discuss your plan',
      cards: [
        { name: 'Strategy Consultation', price: '€100', meta: '60 minutes', desc: 'For a concrete question, a second opinion or a decision you need to make now.', bullets: ['One-to-one session', 'Clear next steps'] },
        { name: 'Admissions Blueprint', price: '€240', meta: 'fixed price', desc: 'A profile assessment and written plan that sets the direction for the process.', bullets: ['Profile intake', '60-minute strategy session', 'Written plan within 5 business days'] },
        { name: 'University Direction', price: 'from €490', meta: 'scope-based', desc: 'A reasoned shortlist with deadlines, costs and key requirements mapped out.', bullets: ['Up to 8 programs', 'Deadline & cost map', 'One revision'] },
        { name: 'Full Application Partnership', price: '€1,400–2,500', meta: 'application cycle', desc: 'Up to four European programs; extra, scholarship-heavy and complex UK/US applications are quoted separately.', bullets: ['Plan & shortlist', 'Two review rounds per agreed document', 'Defined support period'], featured: true },
      ],
    },
    process: {
      kicker: 'How it works', title: 'One process. Three clear phases.',
      steps: [
        ['Understand your starting point', 'Your profile, interests, budget, deadlines and constraints—with candour and without generic advice.'],
        ['Map a realistic route', 'Priorities, a reasoned shortlist and a concrete work plan built around your goal.'],
        ['Apply with structure', 'We ask the right questions and give honest feedback; the ideas, voice and final decisions remain yours.'],
      ],
    },
    principles: {
      kicker: 'Boutique by design', title: 'We are not a university sales channel.',
      body: 'Recommendations are based on your profile, goals, budget and deadlines. We do not promise admission; we build a process where every choice has a reason.',
      labels: [['01', 'Independent assessment'], ['02', 'Direct adviser access'], ['03', 'Transparent scope & fees']],
      ethicsTitle: 'Your application remains yours.',
      ethicsBody: 'We do not write essays for applicants or promise admission or scholarships. We provide structure, the right questions and detailed feedback so you can present your own story clearly and authentically.',
    },
    pricing: {
      kicker: 'Transparent pricing', title: 'Know the range before you pay.',
      body: 'Complete engagements typically range from €1,400 to €2,500, depending on the number of programs, scholarship work and complexity.',
      table: [
        ['Introductory fit call', '15 min', '€0'], ['Expert consultation', '60 min', '€100'],
        ['Admissions Blueprint', 'fixed', '€240'], ['University Direction', 'from', '€490'],
        ['First standard application', 'from', '€250'], ['Scholarship advisory', 'from', '€200'],
        ['Interview preparation', 'from', '€150'], ['Private mentoring', 'per hour', '€110'],
      ],
      note: 'We confirm the final scope and fee in writing before payment.',
    },
    faq: {
      kicker: 'Frequently asked', title: 'Before you book.',
      items: [
        ['How do you help applicants build the strongest possible application?', 'We work individually and guide each applicant against the criteria of the specific programme — from strategy and programme choice to arguments, documents and interviews. Generic writing, including text produced by automated tools without personal context, often fails to show motivation, experience and genuine programme fit. Our experts have experience with DAAD, Erasmus Mundus, OeAD and France Excellence scholarship programmes.'],
        ['Do you support bachelor’s and master’s applicants?', 'Yes. We work with students and families targeting international bachelor’s and master’s programs, primarily across Europe.'],
        ['Do you write motivation letters for applicants?', 'No. We help you develop structure, arguments and your own voice, then provide detailed feedback and revisions.'],
        ['Can I purchase just one service?', 'Yes. You can start with a consultation, strategy or shortlist without committing to a full package.'],
        ['Which languages do you work in?', 'Guidance and content are available in Bosnian, Croatian, Serbian/Montenegrin, English, German and French.'],
        ['What happens in the free call?', 'We learn about your goals, timeline and needs and assess mutual fit. It does not include a detailed profile review or university shortlist.'],
      ],
    },
    booking: {
      kicker: 'Your next step', title: '15 minutes to see if the fit is right.',
      body: 'The calendar connects you with one available team member and detects your time zone automatically. The call covers goals, timing and mutual fit.',
      event: 'Free introductory call', duration: '15 minutes', location: 'Online · video call', timezone: 'Automatic time zone',
      button: 'Open booking calendar', pending: 'Booking calendar ready to connect',
      paid: 'For a detailed profile review, book a 60-minute strategy consultation.',
    },
    footer: { line: 'Clarity for every step.', description: 'Independent guidance for international university applications.', rights: 'All rights reserved.' },
  },
  de: {
    localeName: 'Deutsch',
    nav: { services: 'Leistungen', process: 'Ablauf', pricing: 'Preise', faq: 'FAQ', book: 'Gespräch buchen' },
    hero: {
      eyebrow: 'Bewerbungen an europäischen Hochschulen · Beratung in Ihrer Sprache', titleA: 'Im Ausland studieren.', titleB: 'Mit einem klaren Plan bewerben.',
      body: 'Unabhängige Beratung für europäische Bachelor- und Masterbewerbungen – Programme, Kosten, Förderung und Fristen in einem realistischen Plan.',
      primary: 'Nächsten Schritt klären — 15 Min. kostenlos', secondary: 'So arbeiten wir',
    },
    trust: ['Unabhängige Beratung', 'Persönliche Begleitung', 'Transparente Preise'],
    route: {
      title: 'Ihr Bewerbungsweg', live: 'klar', next: 'Nächster Schritt', free: '15 Min. · kostenlos',
      stops: [['PROFIL', 'Ausgangslage'], ['RICHTUNG', 'Passende Programme'], ['BEWERBUNG', 'Eine klare Geschichte']],
      note: 'Wir wählen keine Universität für Sie. Wir helfen Ihnen, besser zu entscheiden.',
    },
    signals: {
      kicker: 'Vor der ersten Bewerbung', title: 'Zuerst planen wir die Entscheidungen, die wirklich zählen.',
      body: 'Eine gute Strategie verbindet akademische Eignung, Finanzen, Fristen und Ambition. Erst dann wählen wir Programme und entwickeln die Bewerbung.',
      items: [
        ['Akademische Eignung', 'Wir prüfen, wo Ihr Profil konkurrenzfähig ist und wo Ihre Geschichte geschärft werden muss.'],
        ['Budget & Förderung', 'Kosten und realistische Finanzierungsmöglichkeiten fließen von Anfang an ein.'],
        ['Programme & Länder', 'Keine generischen Listen; jede Empfehlung braucht einen klaren Grund.'],
        ['Fristen & Tempo', 'Wir übersetzen einen komplexen Prozess in Prioritäten, Termine und einen Wochenrhythmus.'],
      ],
    },
    services: {
      kicker: 'Leistungen', title: 'So fokussiert oder umfassend, wie Sie es benötigen.',
      body: 'Starten Sie mit einer Strategiesitzung oder arbeiten Sie mit uns durch den gesamten Bewerbungszyklus.', cta: 'Plan besprechen',
      cards: [
        { name: 'Strategieberatung', price: '100 €', meta: '60 Minuten', desc: 'Für eine konkrete Frage, eine zweite Einschätzung oder eine anstehende Entscheidung.', bullets: ['Persönliches Gespräch', 'Klare nächste Schritte'] },
        { name: 'Admissions Blueprint', price: '240 €', meta: 'Festpreis', desc: 'Profilanalyse und schriftlicher Plan als Richtung für den gesamten Prozess.', bullets: ['Profilaufnahme', '60-minütiges Strategiegespräch', 'Schriftlicher Plan in 5 Werktagen'] },
        { name: 'University Direction', price: 'ab 490 €', meta: 'nach Umfang', desc: 'Begründete Programmauswahl mit Fristen, Kosten und Anforderungen.', bullets: ['Bis zu 8 Programme', 'Fristen- und Kostenplan', 'Eine Überarbeitung'] },
        { name: 'Full Application Partnership', price: '1.400–2.500 €', meta: 'Bewerbungszyklus', desc: 'Bis zu vier europäische Programme; weitere, stipendienintensive und komplexe UK/US-Bewerbungen werden separat angeboten.', bullets: ['Plan & Shortlist', 'Zwei Feedbackrunden je vereinbartem Dokument', 'Definierter Betreuungszeitraum'], featured: true },
      ],
    },
    process: {
      kicker: 'So arbeiten wir', title: 'Ein Prozess. Drei klare Phasen.',
      steps: [
        ['Ausgangslage verstehen', 'Profil, Interessen, Budget, Fristen und Grenzen – ehrlich und ohne allgemeine Standardtipps.'],
        ['Einen realistischen Weg planen', 'Prioritäten, eine begründete Auswahl und ein konkreter Arbeitsplan für Ihr Ziel.'],
        ['Strukturiert bewerben', 'Wir stellen die richtigen Fragen und geben ehrliches Feedback; Ideen, Stimme und Entscheidungen bleiben Ihre.'],
      ],
    },
    principles: {
      kicker: 'Bewusst persönlich', title: 'Wir sind kein Vertriebskanal für Universitäten.',
      body: 'Unsere Empfehlungen basieren auf Ihrem Profil, Ihren Zielen, Ihrem Budget und Ihren Fristen. Wir versprechen keine Zulassung; wir schaffen einen Prozess, in dem jede Entscheidung begründet ist.',
      labels: [['01', 'Unabhängige Einschätzung'], ['02', 'Direkter Beraterkontakt'], ['03', 'Transparenter Umfang & Preis']],
      ethicsTitle: 'Ihre Bewerbung bleibt Ihre eigene.',
      ethicsBody: 'Wir schreiben keine Essays für Bewerber:innen und versprechen weder Zulassung noch Stipendien. Wir geben Struktur, stellen die richtigen Fragen und liefern detailliertes Feedback.',
    },
    pricing: {
      kicker: 'Transparente Preise', title: 'Kennen Sie den Rahmen vor der Zahlung.',
      body: 'Komplette Begleitungen liegen meist zwischen 1.400 und 2.500 €, abhängig von Programmanzahl, Stipendienarbeit und Komplexität.',
      table: [
        ['Kennenlerngespräch', '15 Min.', '0 €'], ['Strategieberatung', '60 Min.', '100 €'],
        ['Admissions Blueprint', 'Festpreis', '240 €'], ['University Direction', 'ab', '490 €'],
        ['Erste Standardbewerbung', 'ab', '250 €'], ['Stipendienberatung', 'ab', '200 €'],
        ['Interviewvorbereitung', 'ab', '150 €'], ['Persönliches Mentoring', 'pro Std.', '110 €'],
      ],
      note: 'Den endgültigen Umfang und Preis bestätigen wir vor der Zahlung schriftlich.',
    },
    faq: {
      kicker: 'Häufige Fragen', title: 'Bevor Sie buchen.',
      items: [
        ['Wie helfen Sie Bewerber:innen, eine möglichst starke Bewerbung zu erstellen?', 'Wir arbeiten individuell und richten jede Bewerbung konsequent an den Kriterien des jeweiligen Programms aus — von Strategie und Programmauswahl bis zu Argumentation, Unterlagen und Interview. Generische Texte, einschließlich automatisch erstellter Inhalte ohne persönlichen Kontext, zeigen Motivation, Erfahrung und tatsächliche Passung häufig nicht ausreichend. Unser Team verfügt über Erfahrung mit den Stipendienprogrammen DAAD, Erasmus Mundus, OeAD und France Excellence.'],
        ['Begleiten Sie Bachelor- und Masterbewerbungen?', 'Ja. Wir arbeiten mit Schüler:innen, Studierenden und Familien für internationale Bachelor- und Masterprogramme, vor allem in Europa.'],
        ['Schreiben Sie Motivationsschreiben für Bewerber:innen?', 'Nein. Wir helfen bei Struktur, Argumenten und der eigenen Stimme und geben anschließend detailliertes Feedback.'],
        ['Kann ich nur eine einzelne Leistung buchen?', 'Ja. Sie können mit einer Beratung, Strategie oder Auswahl starten, ohne ein Gesamtpaket zu buchen.'],
        ['In welchen Sprachen beraten Sie?', 'Beratung und Inhalte sind auf Bosnisch, Kroatisch, Serbisch/Montenegrinisch, Englisch, Deutsch und Französisch verfügbar.'],
        ['Was beinhaltet das kostenlose Gespräch?', 'Wir lernen Ziele, Zeitplan und Bedarf kennen und prüfen die Zusammenarbeit. Eine ausführliche Profilanalyse oder Hochschulliste ist nicht enthalten.'],
      ],
    },
    booking: {
      kicker: 'Nächster Schritt', title: '15 Minuten, um die Zusammenarbeit zu prüfen.',
      body: 'Der Kalender verbindet Sie mit einem verfügbaren Teammitglied und erkennt Ihre Zeitzone automatisch. Das Gespräch klärt Ziele, Zeitplan und gegenseitige Passung.',
      event: 'Kostenloses Kennenlerngespräch', duration: '15 Minuten', location: 'Online · Videoanruf', timezone: 'Automatische Zeitzone',
      button: 'Buchungskalender öffnen', pending: 'Buchungskalender bereit zur Verbindung',
      paid: 'Für eine ausführliche Profilanalyse buchen Sie eine 60-minütige Strategieberatung.',
    },
    footer: { line: 'Klarheit bei jedem Schritt.', description: 'Unabhängige Beratung für internationale Hochschulbewerbungen.', rights: 'Alle Rechte vorbehalten.' },
  },
  fr: {
    localeName: 'Français',
    nav: { services: 'Services', process: 'Notre méthode', pricing: 'Tarifs', faq: 'Questions', book: 'Réserver un appel' },
    hero: {
      eyebrow: 'Candidatures universitaires en Europe · conseil dans votre langue', titleA: 'Étudiez à l’étranger.', titleB: 'Candidatez avec une stratégie claire.',
      body: 'Un conseil indépendant pour les candidatures en licence et master en Europe — programmes, coûts, financements et échéances réunis dans un plan réaliste.',
      primary: 'Clarifiez la prochaine étape — 15 min offertes', secondary: 'Voir notre méthode',
    },
    trust: ['Conseil indépendant', 'Accompagnement individuel', 'Tarifs transparents'],
    route: {
      title: 'Votre parcours d’admission', live: 'clair', next: 'Prochaine étape', free: '15 min · offert',
      stops: [['PROFIL', 'Point de départ'], ['DIRECTION', 'Bons programmes'], ['CANDIDATURE', 'Une histoire claire']],
      note: 'Nous ne choisissons pas une université à votre place. Nous vous aidons à prendre une meilleure décision.',
    },
    signals: {
      kicker: 'Avant la première candidature', title: 'Nous cartographions d’abord les décisions qui influencent réellement le résultat.',
      body: 'Une stratégie solide relie le profil académique, le budget, les échéances et l’ambition. Ensuite seulement, nous sélectionnons les programmes et construisons la candidature.',
      items: [
        ['Adéquation académique', 'Nous évaluons où votre profil est compétitif et où votre récit doit être renforcé.'],
        ['Budget et financement', 'Les coûts et les sources de financement réalistes font partie du plan dès le premier jour.'],
        ['Programmes et pays', 'Pas de listes génériques : chaque recommandation doit avoir une raison claire.'],
        ['Échéances et rythme', 'Nous transformons un processus complexe en priorités, échéances et rythme hebdomadaire.'],
      ],
    },
    services: {
      kicker: 'Services', title: 'Un accompagnement aussi ciblé — ou complet — que nécessaire.',
      body: 'Commencez par une séance stratégique ou travaillez avec nous pendant tout le cycle de candidature.', cta: 'Parler de votre projet',
      cards: [
        { name: 'Consultation stratégique', price: '100 €', meta: '60 minutes', desc: 'Pour une question précise, un second avis ou une décision à prendre maintenant.', bullets: ['Séance individuelle', 'Prochaines étapes claires'] },
        { name: 'Admissions Blueprint', price: '240 €', meta: 'prix fixe', desc: 'Une évaluation du profil et un plan écrit qui donnent une direction au processus.', bullets: ['Collecte des informations du profil', 'Séance stratégique de 60 minutes', 'Plan écrit sous 5 jours ouvrés'] },
        { name: 'University Direction', price: 'dès 490 €', meta: 'selon le périmètre', desc: 'Une sélection argumentée avec échéances, coûts et exigences clés.', bullets: ['Jusqu’à 8 programmes', 'Carte des délais et coûts', 'Une révision'] },
        { name: 'Full Application Partnership', price: '1 400–2 500 €', meta: 'cycle de candidature', desc: 'Jusqu’à quatre programmes européens ; les candidatures supplémentaires, avec bourses ou complexes au Royaume-Uni/aux États-Unis font l’objet d’un devis séparé.', bullets: ['Plan et sélection', 'Deux révisions par document convenu', 'Période d’accompagnement définie'], featured: true },
      ],
    },
    process: {
      kicker: 'Notre méthode', title: 'Un processus. Trois étapes claires.',
      steps: [
        ['Comprendre votre point de départ', 'Votre profil, vos intérêts, votre budget, vos délais et vos contraintes — avec franchise et sans conseils génériques.'],
        ['Tracer un parcours réaliste', 'Des priorités, une sélection argumentée et un plan de travail concret construit autour de votre objectif.'],
        ['Candidater avec méthode', 'Nous posons les bonnes questions et donnons un retour honnête ; les idées, la voix et les décisions finales restent les vôtres.'],
      ],
    },
    principles: {
      kicker: 'Un choix délibérément boutique', title: 'Nous ne sommes pas un canal commercial pour les universités.',
      body: 'Nos recommandations reposent sur votre profil, vos objectifs, votre budget et vos délais. Nous ne promettons pas l’admission ; nous construisons un processus où chaque choix a une raison.',
      labels: [['01', 'Évaluation indépendante'], ['02', 'Accès direct au conseiller'], ['03', 'Périmètre et tarifs transparents']],
      ethicsTitle: 'Votre candidature reste la vôtre.',
      ethicsBody: 'Nous n’écrivons pas les essais à la place des candidats et ne promettons ni admission ni bourse. Nous apportons une structure, les bonnes questions et un retour détaillé.',
    },
    pricing: {
      kicker: 'Tarifs transparents', title: 'Connaissez la fourchette avant de payer.',
      body: 'Un accompagnement complet se situe généralement entre 1 400 € et 2 500 €, selon le nombre de programmes, le travail sur les bourses et la complexité.',
      table: [
        ['Appel de découverte', '15 min', '0 €'], ['Consultation stratégique', '60 min', '100 €'],
        ['Admissions Blueprint', 'forfait', '240 €'], ['University Direction', 'dès', '490 €'],
        ['Première candidature standard', 'dès', '250 €'], ['Conseil en bourses', 'dès', '200 €'],
        ['Préparation à l’entretien', 'dès', '150 €'], ['Mentorat individuel', 'par heure', '110 €'],
      ],
      note: 'Nous confirmons par écrit le périmètre final et le tarif avant tout paiement.',
    },
    faq: {
      kicker: 'Questions fréquentes', title: 'Avant de réserver.',
      items: [
        ['Comment aidez-vous les candidats à construire le meilleur dossier possible ?', 'Nous travaillons de manière individuelle et alignons chaque dossier sur les critères du programme visé — de la stratégie et du choix des programmes aux arguments, documents et entretiens. Les textes génériques, y compris ceux produits par des outils automatisés sans contexte personnel, montrent souvent mal la motivation, l’expérience et l’adéquation réelle avec le programme. Nos spécialistes ont l’expérience des programmes de bourses DAAD, Erasmus Mundus, OeAD et France Excellence.'],
        ['Accompagnez-vous les candidatures en licence et en master ?', 'Oui. Nous travaillons avec des élèves, étudiants et familles visant des programmes internationaux de licence et de master, principalement en Europe.'],
        ['Rédigez-vous les lettres de motivation à la place des candidats ?', 'Non. Nous vous aidons à développer la structure, les arguments et votre propre voix, puis nous apportons un retour détaillé.'],
        ['Puis-je choisir un seul service ?', 'Oui. Vous pouvez commencer par une consultation, une stratégie ou une sélection sans vous engager sur un accompagnement complet.'],
        ['Dans quelles langues travaillez-vous ?', 'Le conseil et les contenus sont disponibles en bosnien, croate, serbe/monténégrin, anglais, allemand et français.'],
        ['Que comprend l’appel gratuit ?', 'Nous découvrons vos objectifs, votre calendrier et vos besoins afin d’évaluer notre adéquation. Il n’inclut pas une analyse détaillée du profil ni une liste d’universités.'],
      ],
    },
    booking: {
      kicker: 'Prochaine étape', title: '15 minutes pour vérifier si nous sommes faits pour travailler ensemble.',
      body: 'Le calendrier vous met en relation avec un membre disponible de l’équipe et détecte automatiquement votre fuseau horaire. L’appel porte sur vos objectifs, vos délais et notre adéquation.',
      event: 'Appel découverte gratuit', duration: '15 minutes', location: 'En ligne · visioconférence', timezone: 'Fuseau horaire automatique',
      button: 'Ouvrir le calendrier', pending: 'Calendrier de réservation prêt à être connecté',
      paid: 'Pour une analyse détaillée du profil, réservez une consultation stratégique de 60 minutes.',
    },
    footer: { line: 'De la clarté à chaque étape.', description: 'Conseil indépendant pour les candidatures universitaires internationales.', rights: 'Tous droits réservés.' },
  },
} as const;

export type Locale = keyof typeof translations;
