import type { Locale } from './content';

export const locales: Locale[] = ['sr', 'hr', 'bs', 'en', 'de', 'fr'];

export const localeMeta: Record<Locale, { html: string; hrefLang: string; short: string; native: string }> = {
  hr: { html: 'hr', hrefLang: 'hr-HR', short: 'HR', native: 'Hrvatski' },
  bs: { html: 'bs', hrefLang: 'bs-BA', short: 'BS', native: 'Bosanski / bošnjački' },
  sr: { html: 'sr-Latn', hrefLang: 'sr-Latn', short: 'SR/ME', native: 'Srpski / crnogorski' },
  en: { html: 'en', hrefLang: 'en', short: 'EN', native: 'English' },
  de: { html: 'de', hrefLang: 'de-DE', short: 'DE', native: 'Deutsch' },
  fr: { html: 'fr', hrefLang: 'fr-FR', short: 'FR', native: 'Français' },
};

export function isLocale(value: string): value is Locale {
  return locales.includes(value as Locale);
}

type UtilityCopy = {
  skip: string;
  navigation: string;
  language: string;
  currentLanguage: string;
  contact: string;
  privacy: string;
  serviceInfo: string;
  external: string;
  unavailable: string;
  pricingDetails: string;
  pricingScope: string;
  core: string;
  close: string;
  contactTitle: string;
  contactLead: string;
  contactDirect: string;
  contactPending: string;
  contactTiming: string;
  contactTimingBody: string;
  contactPrepare: string;
  contactPrepareItems: string[];
  privacyTitle: string;
  privacyLead: string;
  privacySections: Array<[string, string]>;
  serviceTitle: string;
  serviceLead: string;
  serviceSections: Array<[string, string]>;
  legalStatus: string;
  backHome: string;
  teamNote: string;
};

export const utility: Record<Locale, UtilityCopy> = {
  hr: {
    skip: 'Preskoči na sadržaj', navigation: 'Glavna navigacija', language: 'Jezik', currentLanguage: 'Odaberi jezik', contact: 'Kontakt', privacy: 'Privatnost i kolačići', serviceInfo: 'Informacije o usluzi', external: 'Otvara vanjsku stranicu', unavailable: 'Kalendar još nije aktivan', pricingDetails: 'Detaljne cijene i dodaci', pricingScope: 'Prva četiri retka sažimaju osnovnu ponudu. Preostali redci su samostalne usluge ili dodaci. Konačan opseg potvrđujemo pisanim putem prije plaćanja.', core: 'Cjelovita podrška', close: 'Zatvori',
    contactTitle: 'Razgovarajmo o vašem sljedećem koraku.', contactLead: 'Pošaljite opći upit e-poštom ili rezervirajte besplatan uvodni razgovor od 15 minuta.', contactDirect: 'Izravni kontakt', contactPending: 'Kontaktirajte nas na adria.admissions@gmail.com.', contactTiming: 'Kada se javljamo', contactTimingBody: 'Na upite odgovaramo radnim danom.', contactPrepare: 'Za korisniji prvi razgovor pripremite', contactPrepareItems: ['zemlju i razinu studija', 'okvirni budžet i važne rokove', '2–3 najveće nedoumice'],
    privacyTitle: 'Privatnost i kolačići', privacyLead: 'Stranica ne koristi analitiku ni marketinške kolačiće. Upite možete poslati izravno e-poštom ili rezervirati razgovor putem vanjskog Calendly kalendara.', privacySections: [['Što stranica pohranjuje', 'Ne pohranjujemo jezične postavke ni druge podatke u vaš preglednik. Jezik je dio URL-a. Hosting može obrađivati standardne tehničke zapise i postaviti nužni sigurnosni kolačić radi zaštite i dostupnosti.'], ['Vanjski kalendar', 'Ako otvorite Calendly, napuštate ovu stranicu i vrijede pravila privatnosti tog pružatelja.'], ['Kontakt i pravna osnova', 'Za zahtjeve povezane s privatnošću javite se na adria.admissions@gmail.com. Puni podaci voditelja obrade bit će dodani nakon registracije poslovnog subjekta.']],
    serviceTitle: 'Informacije o usluzi', serviceLead: 'Jasan sažetak opsega, cijena i granica savjetovanja Adria Admissions.', serviceSections: [['Neovisnost', 'Adria Admissions nije prodajni kanal sveučilišta. Preporuke se temelje na profilu, ciljevima, budžetu i rokovima kandidata.'], ['Autorstvo i ishodi', 'Ne pišemo eseje umjesto kandidata i ne jamčimo upis ili stipendiju. Konačne odluke donose sveučilišta i stipendijska tijela.'], ['Opseg i plaćanje', 'Konačan opseg, cijena, raspored, uvjeti otkazivanja i informacije o pravu na odustanak dostavljaju se pisanim putem prije plaćanja. Aktualne zahtjeve uvijek treba provjeriti u službenim izvorima sveučilišta.']],
    legalStatus: 'Informativna verzija · puni podaci poslovnog subjekta bit će dodani nakon registracije, prije sklapanja ugovora ili naplate.', backHome: 'Natrag na naslovnicu', teamNote: 'Na uvodnom razgovoru upoznat ćete jednog člana našeg tima. Svaki član tima završio je dio svojeg obrazovanja u inozemstvu i iz osobnog iskustva poznaje međunarodni obrazovni put.',
  },
  bs: {
    skip: 'Preskočite na sadržaj', navigation: 'Glavna navigacija', language: 'Jezik', currentLanguage: 'Izaberite jezik', contact: 'Kontakt', privacy: 'Privatnost i kolačići', serviceInfo: 'Informacije o usluzi', external: 'Otvara vanjsku stranicu', unavailable: 'Kalendar još nije aktivan', pricingDetails: 'Detaljne cijene i dodaci', pricingScope: 'Prva četiri reda sažimaju osnovnu ponudu. Preostali redovi su samostalne usluge ili dodaci. Konačan obim potvrđujemo pisanim putem prije plaćanja.', core: 'Cjelovita podrška', close: 'Zatvori',
    contactTitle: 'Razgovarajmo o vašem sljedećem koraku.', contactLead: 'Pošaljite opći upit e-poštom ili rezervišite besplatan uvodni razgovor od 15 minuta.', contactDirect: 'Direktan kontakt', contactPending: 'Kontaktirajte nas na adria.admissions@gmail.com.', contactTiming: 'Kada odgovaramo', contactTimingBody: 'Na upite odgovaramo radnim danima.', contactPrepare: 'Za korisniji prvi razgovor pripremite', contactPrepareItems: ['zemlju i nivo studija', 'okvirni budžet i važne rokove', '2–3 najveće nedoumice'],
    privacyTitle: 'Privatnost i kolačići', privacyLead: 'Stranica ne koristi analitiku ni marketinške kolačiće. Upite možete poslati direktno e-poštom ili rezervisati razgovor putem vanjskog Calendly kalendara.', privacySections: [['Šta stranica pohranjuje', 'Ne pohranjujemo jezične postavke ni druge podatke u vaš preglednik. Jezik je dio URL-a. Hosting može obrađivati standardne tehničke zapise i postaviti neophodan sigurnosni kolačić radi zaštite i dostupnosti.'], ['Vanjski kalendar', 'Ako otvorite Calendly, napuštate ovu stranicu i važe pravila privatnosti tog pružatelja.'], ['Kontakt i pravna osnova', 'Za zahtjeve povezane s privatnošću javite se na adria.admissions@gmail.com. Puni podaci voditelja obrade bit će dodani nakon registracije poslovnog subjekta.']],
    serviceTitle: 'Informacije o usluzi', serviceLead: 'Jasan sažetak obima, cijena i granica savjetovanja Adria Admissions.', serviceSections: [['Nezavisnost', 'Adria Admissions nije prodajni kanal univerziteta. Preporuke se zasnivaju na profilu, ciljevima, budžetu i rokovima kandidata.'], ['Autorstvo i ishodi', 'Ne pišemo eseje umjesto kandidata i ne garantujemo prijem ili stipendiju. Konačne odluke donose univerziteti i stipendijska tijela.'], ['Obim i plaćanje', 'Konačan obim, cijena, raspored, uslovi otkazivanja i informacije o pravu na odustanak dostavljaju se pisanim putem prije plaćanja. Aktuelne zahtjeve uvijek treba provjeriti u službenim izvorima univerziteta.']],
    legalStatus: 'Informativna verzija · puni podaci poslovnog subjekta bit će dodani nakon registracije, prije sklapanja ugovora ili naplate.', backHome: 'Nazad na naslovnu', teamNote: 'Na uvodnom razgovoru upoznat ćete jednog člana našeg tima. Svaki član tima završio je dio svog obrazovanja u inostranstvu i iz ličnog iskustva poznaje međunarodni obrazovni put.',
  },
  sr: {
    skip: 'Preskočite na sadržaj', navigation: 'Glavna navigacija', language: 'Jezik', currentLanguage: 'Izaberite jezik', contact: 'Kontakt', privacy: 'Privatnost i kolačići', serviceInfo: 'Informacije o usluzi', external: 'Otvara spoljnu stranicu', unavailable: 'Kalendar još nije aktivan', pricingDetails: 'Detaljne cene i dodaci', pricingScope: 'Prva četiri reda sažimaju osnovnu ponudu. Preostali redovi su samostalne usluge ili dodaci. Konačan obim potvrđujemo pisanim putem pre plaćanja.', core: 'Celovita podrška', close: 'Zatvori',
    contactTitle: 'Razgovarajmo o vašem sledećem koraku.', contactLead: 'Pošaljite opšti upit e-poštom ili rezervišite besplatan uvodni razgovor od 15 minuta.', contactDirect: 'Direktan kontakt', contactPending: 'Kontaktirajte nas na adria.admissions@gmail.com.', contactTiming: 'Kada odgovaramo', contactTimingBody: 'Na upite odgovaramo radnim danima.', contactPrepare: 'Za korisniji prvi razgovor pripremite', contactPrepareItems: ['zemlju i nivo studija', 'okvirni budžet i važne rokove', '2–3 najveće nedoumice'],
    privacyTitle: 'Privatnost i kolačići', privacyLead: 'Stranica ne koristi analitiku ni marketinške kolačiće. Upite možete poslati direktno e-poštom ili rezervisati razgovor putem spoljnog Calendly kalendara.', privacySections: [['Šta stranica čuva', 'Ne čuvamo jezičke postavke niti druge podatke u vašem pregledaču. Jezik je deo URL-a. Hosting može obrađivati standardne tehničke zapise i postaviti neophodan bezbednosni kolačić radi zaštite i dostupnosti.'], ['Spoljni kalendar', 'Ako otvorite Calendly, napuštate ovu stranicu i važe pravila privatnosti tog pružaoca.'], ['Kontakt i pravni osnov', 'Za zahteve povezane s privatnošću javite se na adria.admissions@gmail.com. Puni podaci rukovaoca biće dodati nakon registracije poslovnog subjekta.']],
    serviceTitle: 'Informacije o usluzi', serviceLead: 'Jasan sažetak obima, cena i granica savetovanja Adria Admissions.', serviceSections: [['Nezavisnost', 'Adria Admissions nije prodajni kanal univerziteta. Preporuke se zasnivaju na profilu, ciljevima, budžetu i rokovima kandidata.'], ['Autorstvo i ishodi', 'Ne pišemo eseje umesto kandidata i ne garantujemo prijem ili stipendiju. Konačne odluke donose univerziteti i stipendijska tela.'], ['Obim i plaćanje', 'Konačan obim, cena, raspored, uslovi otkazivanja i informacije o pravu na odustanak dostavljaju se pisanim putem pre plaćanja. Aktuelne zahteve uvek treba proveriti u zvaničnim izvorima univerziteta.']],
    legalStatus: 'Informativna verzija · puni podaci poslovnog subjekta biće dodati nakon registracije, pre sklapanja ugovora ili naplate.', backHome: 'Nazad na početnu', teamNote: 'Na uvodnom razgovoru upoznaćete jednog člana našeg tima. Svaki član tima završio je deo svog obrazovanja u inostranstvu i iz ličnog iskustva poznaje međunarodni obrazovni put.',
  },
  en: {
    skip: 'Skip to content', navigation: 'Main navigation', language: 'Language', currentLanguage: 'Choose language', contact: 'Contact', privacy: 'Privacy & cookies', serviceInfo: 'Service information', external: 'Opens an external site', unavailable: 'Calendar not active yet', pricingDetails: 'Detailed pricing and add-ons', pricingScope: 'The first four rows summarize the core offer. The remaining rows are standalone services or add-ons. We confirm the final scope in writing before payment.', core: 'Complete support', close: 'Close',
    contactTitle: 'Let’s discuss your next step.', contactLead: 'Send a general email enquiry or book a free 15-minute introductory call.', contactDirect: 'Direct contact', contactPending: 'Contact us at adria.admissions@gmail.com.', contactTiming: 'When we reply', contactTimingBody: 'We answer enquiries on business days.', contactPrepare: 'For a more useful first call, prepare', contactPrepareItems: ['target country and study level', 'approximate budget and key deadlines', 'your 2–3 biggest uncertainties'],
    privacyTitle: 'Privacy & cookies', privacyLead: 'This site uses no analytics or marketing cookies. You can contact us directly by email or book a call through the external Calendly calendar.', privacySections: [['What this site stores', 'We do not save language preferences or other data in your browser. The language is part of the URL. Hosting may process standard technical logs and set a strictly necessary security cookie for protection and availability.'], ['External calendar', 'If you open Calendly, you leave this site and that provider’s privacy rules apply.'], ['Contact and legal basis', 'For privacy requests, contact adria.admissions@gmail.com. Full controller details will be added after the business entity is registered.']],
    serviceTitle: 'Service information', serviceLead: 'A clear summary of the scope, prices and boundaries of Adria Admissions guidance.', serviceSections: [['Independence', 'Adria Admissions is not a university sales channel. Recommendations are based on the applicant’s profile, goals, budget and deadlines.'], ['Authorship and outcomes', 'We do not write essays for applicants or guarantee admission or funding. Universities and scholarship bodies make all final decisions.'], ['Scope and payment', 'The final scope, price, schedule, cancellation terms and statutory withdrawal information are provided in writing before payment. Current requirements should always be verified on official university sources.']],
    legalStatus: 'Informational version · full business details will be added after registration, before any contract or payment.', backHome: 'Back to home', teamNote: 'During the introductory call, you will meet one member of our team. Every team member completed part of their education abroad and understands the international education journey from personal experience.',
  },
  de: {
    skip: 'Zum Inhalt springen', navigation: 'Hauptnavigation', language: 'Sprache', currentLanguage: 'Sprache wählen', contact: 'Kontakt', privacy: 'Datenschutz & Cookies', serviceInfo: 'Leistungsinformationen', external: 'Öffnet eine externe Website', unavailable: 'Kalender noch nicht aktiv', pricingDetails: 'Preisübersicht und Zusatzmodule', pricingScope: 'Die ersten vier Zeilen fassen das Kernangebot zusammen. Die übrigen Zeilen sind Einzelleistungen oder Zusatzmodule. Den endgültigen Umfang bestätigen wir vor der Zahlung schriftlich.', core: 'Komplette Begleitung', close: 'Schließen',
    contactTitle: 'Sprechen wir über Ihren nächsten Schritt.', contactLead: 'Senden Sie eine allgemeine E-Mail-Anfrage oder buchen Sie ein kostenloses 15-minütiges Kennenlerngespräch.', contactDirect: 'Direkter Kontakt', contactPending: 'Kontaktieren Sie uns unter adria.admissions@gmail.com.', contactTiming: 'Wann wir antworten', contactTimingBody: 'Wir beantworten Anfragen an Werktagen.', contactPrepare: 'Für ein hilfreiches Erstgespräch benötigen Sie', contactPrepareItems: ['Zielland und Studienniveau', 'ungefähres Budget und wichtige Fristen', 'Ihre 2–3 größten Unsicherheiten'],
    privacyTitle: 'Datenschutz & Cookies', privacyLead: 'Diese Website verwendet weder Analyse- noch Marketing-Cookies. Sie können uns direkt per E-Mail kontaktieren oder über den externen Calendly-Kalender ein Gespräch buchen.', privacySections: [['Was diese Website speichert', 'Wir speichern keine Sprachwahl oder anderen Daten in Ihrem Browser. Die Sprache ist Teil der URL. Der Hosting-Anbieter kann technische Standardprotokolle verarbeiten und ein unbedingt erforderliches Sicherheits-Cookie für Schutz und Verfügbarkeit setzen.'], ['Externer Kalender', 'Wenn Sie Calendly öffnen, verlassen Sie diese Website; es gelten die Datenschutzregeln des Anbieters.'], ['Kontakt und Rechtsgrundlage', 'Für Datenschutzanfragen wenden Sie sich an adria.admissions@gmail.com. Vollständige Angaben zum Verantwortlichen werden nach der Registrierung des Unternehmens ergänzt.']],
    serviceTitle: 'Leistungsinformationen', serviceLead: 'Eine klare Zusammenfassung von Umfang, Preisen und Grenzen der Beratung von Adria Admissions.', serviceSections: [['Unabhängigkeit', 'Adria Admissions ist kein Vertriebskanal für Universitäten. Empfehlungen beruhen auf Profil, Zielen, Budget und Fristen der Bewerber:innen.'], ['Urheberschaft und Ergebnisse', 'Wir schreiben keine Essays für Bewerber:innen und garantieren weder Zulassung noch Finanzierung. Die endgültigen Entscheidungen treffen Universitäten und Stipendiengeber.'], ['Umfang und Zahlung', 'Der endgültige Umfang, Preis, Zeitplan, Stornobedingungen und gesetzliche Widerrufsinformationen werden vor der Zahlung schriftlich mitgeteilt. Aktuelle Anforderungen sind stets auf offiziellen Hochschulseiten zu prüfen.']],
    legalStatus: 'Informationsversion · vollständige Unternehmensangaben folgen nach der Registrierung, vor Vertragsschluss oder Zahlung.', backHome: 'Zurück zur Startseite', teamNote: 'Im Kennenlerngespräch lernen Sie ein Mitglied unseres Teams kennen. Jedes Teammitglied hat einen Teil seiner Ausbildung im Ausland absolviert und kennt den internationalen Bildungsweg aus eigener Erfahrung.',
  },
  fr: {
    skip: 'Aller au contenu', navigation: 'Navigation principale', language: 'Langue', currentLanguage: 'Choisir la langue', contact: 'Contact', privacy: 'Confidentialité et cookies', serviceInfo: 'Informations sur le service', external: 'Ouvre un site externe', unavailable: 'Calendrier pas encore actif', pricingDetails: 'Tarifs détaillés et options', pricingScope: 'Les quatre premières lignes résument l’offre principale. Les autres correspondent à des services individuels ou à des options. Le périmètre final est confirmé par écrit avant paiement.', core: 'Accompagnement complet', close: 'Fermer',
    contactTitle: 'Parlons de votre prochaine étape.', contactLead: 'Envoyez une demande générale par e-mail ou réservez un appel découverte gratuit de 15 minutes.', contactDirect: 'Contact direct', contactPending: 'Contactez-nous à adria.admissions@gmail.com.', contactTiming: 'Quand nous répondons', contactTimingBody: 'Nous répondons les jours ouvrés.', contactPrepare: 'Pour un premier échange plus utile, préparez', contactPrepareItems: ['le pays visé et le niveau d’études', 'le budget approximatif et les échéances clés', 'vos 2–3 principales incertitudes'],
    privacyTitle: 'Confidentialité et cookies', privacyLead: 'Ce site n’utilise ni mesure d’audience ni cookies marketing. Vous pouvez nous contacter directement par e-mail ou réserver un appel via le calendrier Calendly externe.', privacySections: [['Ce que ce site stocke', 'Nous n’enregistrons pas votre choix de langue ni d’autres données dans votre navigateur. La langue fait partie de l’URL. L’hébergeur peut traiter des journaux techniques standard et déposer un cookie de sécurité strictement nécessaire à la protection et à la disponibilité du site.'], ['Calendrier externe', 'Si vous ouvrez Calendly, vous quittez ce site et les règles de confidentialité de ce fournisseur s’appliquent.'], ['Contact et base juridique', 'Pour toute demande relative à la confidentialité, écrivez à adria.admissions@gmail.com. Les informations complètes sur le responsable du traitement seront ajoutées après l’immatriculation de l’entreprise.']],
    serviceTitle: 'Informations sur le service', serviceLead: 'Un résumé clair du périmètre, des tarifs et des limites de l’accompagnement de Adria Admissions.', serviceSections: [['Indépendance', 'Adria Admissions n’est pas un canal commercial pour les universités. Les recommandations reposent sur le profil, les objectifs, le budget et les délais de la personne candidate.'], ['Auteur et résultats', 'Nous n’écrivons pas les essais à la place des candidats et ne garantissons ni admission ni financement. Les universités et organismes de bourses prennent toutes les décisions finales.'], ['Périmètre et paiement', 'Le périmètre final, le prix, le calendrier, les conditions d’annulation et les informations légales sur la rétractation sont transmis par écrit avant paiement. Les exigences actuelles doivent toujours être vérifiées auprès des sources officielles des universités.']],
    legalStatus: 'Version informative · les informations complètes sur l’entreprise seront ajoutées après son immatriculation, avant tout contrat ou paiement.', backHome: 'Retour à l’accueil', teamNote: 'Lors de l’appel découverte, vous rencontrerez un membre de notre équipe. Chaque membre de l’équipe a effectué une partie de sa formation à l’étranger et connaît le parcours éducatif international par expérience personnelle.',
  },
};
